openapi: 3.0.0
x-stoplight:
  id: 0f56e32f16f60
info:
  title: IFS04 - Rettifica iscrizioni
  x-summary:  Richiede la rettifica dei dati di un’iscrizione o una iscrizione mancante o in eccesso per una studentessa o uno studente che stia frequentando o abbia frequentato.
  version: 1.0.0
  description: |
        Richiede la rettifica dei dati di un’iscrizione o una iscrizione mancante o in eccesso per una studentessa o uno studente che stia frequentando o abbia frequentato.
  contact:
    name: helpdesk
    email: helpdesk@gmail.com
  x-api-id: 00000000-0000-0000-0000-000000000000
  termsOfService: 'http://swagger.io/terms/'
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
paths:
  /rettifiche-iscrizioni/campi:
    get:
      summary: Elenco campi modificabili in una iscrizione
      tags:
        - campi rettifica iscrizione
      parameters: []
      responses:
        '200':
          description: Richiesta eseguita con successo
          content:
            application/json:
              schema:
                type: object
                properties:
                  fields:
                    type: array
                    description: Elenco dei campi modificabili
                    items:
                      $ref: '#/components/schemas/CampoRettifica'
                required:
                  - fields
              examples:
                Example 1:
                  value:
                    fields:
                      - fieldName: instituteCode
                        fieldDescription: Codice dell'istituto
                        fieldType: string
                        fieldPattern: '^[A-Za-z ]+$'
                      - fieldName: instituteName
                        fieldDescription: Nome dell'istituto
                        fieldType: string
                        fieldPattern: '^[A-Za-z ]+$'
                      - fieldName: courseCode
                        fieldDescription: Codice del corso
                        fieldType: string
                        fieldPattern: '^[A-Za-z ]+$'
                      - fieldName: courseName
                        fieldDescription: Nome del corso
                        fieldType: string
                        fieldPattern: '^[A-Za-z ]+$'
                      - fieldName: courseType
                        fieldDescription: Tipologia del corso di studio
                        fieldType: string
                        fieldPattern: '^[A-Za-z ]+$'
                      - fieldName: classCode
                        fieldDescription: Codice della classe
                        fieldType: string
                        fieldPattern: '^[A-Za-z ]+$'
                      - fieldName: className
                        fieldDescription: Nome della classe
                        fieldType: string
                        fieldPattern: '^[A-Za-z ]+$'
                      - fieldName: registrationYear
                        fieldDescription: Anno accademico di immatricolazione
                        fieldType: string
                        fieldPattern: '^[A-Za-z ]+$'
                      - fieldName: enrolmentYear
                        fieldDescription: Ultimo anno accademico in cui risulta l'iscrizione al corso per la studentessa o lo studente
                        fieldType: string
                        fieldPattern: '^[A-Za-z ]+$'
                      - fieldName: courseYear
                        fieldDescription: Ultimo anno in cui risulta l'iscrizione al corso per la studentessa o lo studente
                        fieldType: string
                        fieldPattern: '^[A-Za-z ]+$'
        '500':
          description: Errore interno del server
      operationId: campi-rettifica-iscrizione
      description: Restituisce l'elenco dei campi modificabili in una iscrizione
    parameters: []
  /rettifiche-iscrizioni:
    post:
      summary: Rettifica iscrizione studente
      operationId: rettifica-iscrizione-studente
      tags:
        - rettifica iscrizione
      parameters: []
      responses:
        '200':
          description: Richiesta eseguita con successo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RispostaRettifica'
              examples:
                Example 1:
                  value:
                    rectificationId: 6d183bc572f6b200015a4167
        '404':
          description: Studente non trovato
        '500':
          description: Errore interno del server
      description: Permette di creare una richiesta di rettifica dei dati relativi alle iscrizioni di una studentessa o uno studente.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RichiestaRettifica'
            examples:
              Example 1:
                value:
                  taxCode: RSSMRA80A01F205D
                  enrollmentToEdit:
                    enrollmentId: 908d3e72b51a6f0034e2a11c
                    fieldsToEdit:
                      - fieldName: instituteName
                        oldValue: Università degli studi di Milano
                        newValue: Università degli studi di Roma 'La Sapienza'
                      - fieldName: courseType
                        oldValue: Laurea
                        newValue: Corso di Laurea
                      - fieldName: registrationYear
                        oldValue: 2021/2022
                        newValue: 2022/2023
                      - fieldName: courseYear
                        oldValue: 2° anno
                        newValue: 3° anno
                  rectificationReqText: Testo con la richiesta di rettifica
                  openNotes: Note aperte studentessa o studente
              Example 2:
                value:
                  taxCode: RSSMRA80A01F205D
                  enrollmentToEnter:
                    instituteCode: IFSRM1
                    instituteName: Università degli Studi di Roma 'La Sapienza'
                    courseType: Corso di laurea
                    courseCode: INF101
                    courseName: Ingegneria
                    classCode: L-8
                    className: Ingegneria informatica
                    registrationYear: 2019/2020
                    enrolmentYear: 2021/2022
                    courseYear: 3° anno
                  rectificationReqText: Testo con la richiesta di rettifica
                  openNotes: Note aperte studentessa o studente
          application/xml:
            schema:
              type: object
              properties: {}
        description: ''
    parameters: []
  '/rettifiche-iscrizioni/{taxCode}':
    parameters:
      - schema:
          type: string
        name: taxCode
        in: path
        required: true
        description: Codice Fiscale
    get:
      summary: Elenco rettifiche iscrizioni
      tags:
        - rettifiche iscrizioni
      parameters: []
      responses:
        '200':
          description: Richiesta eseguita con successo
          content:
            application/json:
              schema:
                type: object
                properties:
                  rectifications:
                    type: array
                    items:
                      $ref: '#/components/schemas/Rettifica'
              examples:
                Example 1:
                  value:
                    rectifications:
                      - rectificationId: 6d183bc572f6b200015a4167
                        enrollmentId: 908d3e72b51a6f0034e2a11c
                        state: Presa in carico
                        date: '2023-02-12'
                        rectificationReqText: Modifica dati iscrizione
                        openNotes: Note operte
                      - rectificationId: a8c4910e76b5200001d4f268
                        enrollmentId: 245e6c91b7a82000314fd9a0
                        state: In lavorazione
                        date: '2023-03-18'
                        rectificationReqText: Modifica dati iscrizione
                        openNotes: Note operte
                      - rectificationId: d5f8a7e910c6b2000153a410
                        enrollmentId: 7b93401e2c68b10001ca278f
                        state: Accettata
                        date: '2023-05-02'
                        rectificationReqText: Modifica dati iscrizione
                        openNotes: Note operte
                      - rectificationId: e0a712c6f9b9200001d5f834
                        enrollmentId: c50e9a71b26f21000167a83d
                        state: Rifiutata
                        date: '2023-06-23'
                        rectificationReqText: Modifica dati iscrizione
                        openNotes: Note operte
                Example 2:
                  value:
                    rectifications: []
        '404':
          description: Non è stato possibile trovare la studentessa o lo studente nell'archivio
        '500':
          description: Errore interno del server
      operationId: rettifiche-iscrizioni-studente
      description: 'Permette di recuperare, tramite il codice fiscale, l''elenco delle richieste di rettifica iscrizione di una studentessa o uno studente specifici.'
  '/rettifiche-iscrizioni/{rectificationId}/dettaglio':
    parameters:
      - schema:
          type: string
        name: rectificationId
        in: path
        required: true
        description: Identificativo della rettifica
    get:
      summary: Dettaglio rettifica iscrizione studentessa o studente
      tags:
        - dettaglio rettifica iscrizione
      parameters: []
      responses:
        '200':
          description: Richiesta eseguita con successo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DettaglioRettifica'
              examples:
                Example 1:
                  value:
                    rectificationId: 6d183bc572f6b200015a4167
                    enrollmentId: 908d3e72b51a6f0034e2a11c
                    state: Accettata
                    enrollmentToEdit:
                      enrollmentId: 908d3e72b51a6f0034e2a11c
                      fieldsToEdit:
                        - fieldName: instituteName
                          oldValue: Università degli studi di Milano
                          newValue: Università degli studi di Roma 'La Sapienza'
                        - fieldName: courseType
                          oldValue: Laurea
                          newValue: Corso di Laurea
                        - fieldName: registrationYear
                          oldValue: 2021/2022
                          newValue: 2022/2023
                        - fieldName: courseYear
                          oldValue: 2° anno
                          newValue: 3° anno
                    stateHistory:
                      - state: Accettata
                        date: '2023-06-10'
                        description: Descrizione del passaggio di stato
                      - state: In lavorazione
                        date: '2023-03-05'
                        description: Descrizione del passaggio di stato
                      - state: Presa in carico
                        date: '2023-02-25'
                        description: Descrizione del passaggio di stato
                    rectificationReqText: Testo con la richiesta di rettifica
                    openNotes: Note aperte studentessa o studente
                Example 2:
                  value:
                    rectificationId: 6d183bc572f6b200015a4167
                    enrollmentId: 908d3e72b51a6f0034e2a11c
                    state: Accettata
                    enrollmentToEnter:
                      instituteCode: IFSRM1
                      instituteName: Università degli Studi di Roma 'La Sapienza'
                      courseType: Corso di laurea
                      courseCode: INF101
                      courseName: Ingegneria
                      classCode: L-8
                      className: Ingegneria informatica
                      registrationYear: 2019/2020
                      enrolmentYear: 2021/2022
                      courseYear: 3° anno
                    stateHistory:
                      - state: Accettata
                        date: '2023-06-10'
                        description: Descrizione del passaggio di stato
                      - state: In lavorazione
                        date: '2023-03-05'
                        description: Descrizione del passaggio di stato
                      - state: Presa in carico
                        date: '2023-02-25'
                        description: Descrizione del passaggio di stato
                    rectificationReqText: Testo con la richiesta di rettifica
                    openNotes: Note aperte studentessa o studente
        '404':
          description: Rettifica iscrizione non trovata
        '500':
          description: Errore interno del server
      operationId: dettaglio-rettifica-iscrizione
      description: Permette di recuperare il dettaglio di una richiesta di rettifica iscrizione tramite il suo identificativo.
  /status:
    get:
      summary: Verifica stato delle API (Health Check)
      operationId: check-status
      description: Verificare lo stato di salute del sistema
      tags:
        - health-check
      responses:
        '204':
          description: il servizio è in esecuzione correttamente.
        '500':
          description: il servizio non è in esecuzione.
components:
  schemas:
    CampoRettifica:
      type: object
      x-examples:
        Example 1:
          fieldName: instituteName
          fieldDescription: Nome dell'istituto
          fieldType: string
          fieldPattern: '^[A-Za-z ]+$'
      properties:
        fieldName:
          type: string
          description: Nome del campo
          readOnly: true
        fieldDescription:
          type: string
          description: Descrizione del campo
          readOnly: true
        fieldType:
          type: string
          description: Tipo del campo
          readOnly: true
        fieldPattern:
          type: string
          description: Pattern del campo
          readOnly: true
      required:
        - fieldName
        - fieldDescription
        - fieldType
      description: Dettaglio campo rettifica
      x-stoplight:
        id: 705c3b968ec92
    RichiestaRettifica:
      type: object
      x-examples:
        Example 1:
          taxCode: RSSMRA80A01F205D
          enrollmentToEdit:
            enrollmentId: 908d3e72b51a6f0034e2a11c
            fieldsToEdit:
              - fieldName: instituteName
                oldValue: Università degli studi di Milano
                newValue: Università degli studi di Roma 'La Sapienza'
              - fieldName: courseType
                oldValue: Laurea
                newValue: Corso di Laurea
              - fieldName: registrationYear
                oldValue: 2021/2022
                newValue: 2022/2023
              - fieldName: courseYear
                oldValue: 2° anno
                newValue: 3° anno
          rectificationReqText: Testo con la richiesta di rettifica
          openNotes: Note aperte dello studente/ex studente
        Example 2:
          taxCode: RSSMRA80A01F205D
          enrollmentToEnter:
            instituteCode: IFSRM1
            instituteName: Università degli Studi di Roma 'La Sapienza'
            courseType: Corso di laurea
            courseCode: INF101
            courseName: Ingegneria
            classCode: L-8
            className: Ingegneria informatica
            registrationYear: 2019/2020
            enrolmentYear: 2021/2022
            courseYear: 3° anno
          rectificationReqText: Testo con la richiesta di rettifica
          openNotes: Note aperte studentessa o studente studente
      x-stoplight:
        id: b40e2be27c423
      description: Richiesta creazione rettifica iscrizione di una studentessa o uno studente
      properties:
        taxCode:
          type: string
          description: Codice fiscale
          pattern: '^[A-Z]{6}\d{2}[A-Z]\d{2}[A-Z]\d{3}[A-Z]$'
          example: RSSMRA80A01F205D
          minLength: 16
          maxLength: 16
          readOnly: true
        enrollmentToEdit:
          $ref: '#/components/schemas/ModificaIscrizione'
        enrollmentToEnter:
          $ref: '#/components/schemas/Iscrizione'
        rectificationReqText:
          type: string
          description: Testo con la richiesta di rettifica
          readOnly: true
        openNotes:
          type: string
          description: Note aperte studentessa o studente
          readOnly: true
      required:
        - taxCode
        - rectificationReqText
        - openNotes
    ModificaCampo:
      type: object
      x-examples:
        Example 1:
          fieldName: instituteName
          oldValue: Università degli studi di Milano
          newValue: Università degli studi di Roma 'La Sapienza'
      description: Contiene il nome del campo da modificare con valore vecchio e valore nuovo
      properties:
        fieldName:
          type: string
          description: Nome del campo da modificare
          readOnly: true
        oldValue:
          type: string
          description: Valore attuale del campo
        newValue:
          type: string
          description: Nuovo valore da attribuire al campo
          readOnly: true
      required:
        - fieldName
        - oldValue
        - newValue
      x-stoplight:
        id: 752f77d2e91a7
    ModificaIscrizione:
      title: ModificaIscrizione
      x-stoplight:
        id: cx3v0va134mhh
      type: object
      description: Contiene l'id dell'iscrizione e l'elenco di tutti i campi da modificare
      properties:
        enrollmentId:
          type: string
          description: id dell'iscrizione da modificare
          readOnly: true
        fieldsToEdit:
          type: array
          description: Elenco dei campi da modificare
          items:
            $ref: '#/components/schemas/ModificaCampo'
      required:
        - enrollmentId
        - fieldsToEdit
      x-examples:
        Example 1:
          enrollmentId: 908d3e72b51a6f0034e2a11c
          fieldsToEdit:
            - fieldName: instituteName
              oldValue: Università degli studi di Milano
              newValue: Università degli studi di Roma 'La Sapienza'
            - fieldName: courseType
              oldValue: Laurea
              newValue: Corso di Laurea
            - fieldName: registrationYear
              oldValue: 2021/2022
              newValue: 2022/2023
            - fieldName: courseYear
              oldValue: 2° anno
              newValue: 3° anno
    Iscrizione:
      type: object
      x-examples:
        Example 1:
          _id: 908d3e72b51a6f0034e2a11c
          instituteCode: IFSRM1
          instituteName: Università degli Studi di Roma 'La Sapienza'
          courseType: Corso di laurea
          courseCode: INF101
          courseName: Ingegneria
          classCode: L-8
          className: Ingegneria informatica
          registrationYear: 2019/2020
          enrolmentYear: 2021/2022
          courseYear: 3° anno
      description: Informazioni dettagliate sull'iscrizione
      properties:
        instituteCode:
          type: string
          description: Codice identificativo dell’istituto
          readOnly: true
        instituteName:
          type: string
          description: Denominazione dell’istituto
          readOnly: true
        courseType:
          type: string
          description: Tipologia del corso di studio
          example: laurea, laurea magistrale, dottorato di ricerca, specializzazione, master, formazione professionale
          readOnly: true
        courseCode:
          type: string
          description: Codice del corso
          pattern: '^[A-Z\d]{2,4}\d{2,4}$'
          readOnly: true
        courseName:
          type: string
          description: Denominazione corso
          example: ingegneria, economia, giurisprudenza, medicina, scienze umanistiche, scienze sociali, informatica, arte e design
          readOnly: true
        classCode:
          type: string
          description: Codice identificativo della classe di laurea
          pattern: '^[A-Z]+-\d{1,2}$'
          minLength: 1
          maxLength: 10
          example: L-8
          readOnly: true
        className:
          type: string
          description: Denominazione della classe di laurea
          example: Informatica, Meccanica, Elettronica, Civile
          readOnly: true
        registrationYear:
          type: string
          description: Anno accademico di immatricolazione della studentessa o dello studente
          pattern: '^\d{4}/\d{4}$'
        enrolmentYear:
          type: string
          description: Ultimo anno accademico in cui risulta l'iscrizione al corso della studentessa o dello studente
          example: 2022/2023
          pattern: '^\d{4}/\d{4}$'
          readOnly: true
        courseYear:
          type: string
          description: Ultimo anno in cui risulta l'iscrizione della studentessa o dello studente
          example: 3° anno
          pattern: ^\d+° anno$
          readOnly: true
      required:
        - instituteCode
        - instituteName
        - courseType
        - courseCode
        - courseName
        - classCode
        - className
        - registrationYear
        - enrolmentYear
        - courseYear
    RispostaRettifica:
      type: object
      x-examples:
        Example 1:
          rectificationId: 6d183bc572f6b200015a4167
      description: Risposta di avvenuta creazione richiesta rettifica
      x-stoplight:
        id: 6be27a42c1852
      properties:
        rectificationId:
          type: string
          description: Identificativo della rettifica effettuata
          example: 2A9BCD3E4F567890
          minLength: 16
          maxLength: 24
          readOnly: true
      required:
        - rectificationId
    Rettifica:
      type: object
      x-examples:
        Example 1:
          rectificationId: 6d183bc572f6b200015a4167
          enrollmentId: 908d3e72b51a6f0034e2a11c
          state: Presa in carico
          date: '2023-02-12'
          rectificationReqText: Modifica dati iscrizione
          openNotes: Note operte
      description: Rettifica iscrizione
      properties:
        rectificationId:
          type: string
          description: Identificativo della rettifica
          readOnly: true
        enrollmentId:
          type: string
          description: id dell'iscrizione rettificata
          nullable: true
          readOnly: true
        state:
          type: string
          description: Stato attuale della rettifica
          readOnly: true
        date:
          type: string
          format: date
          description: Data ultima transizione rettifica
          readOnly: true
        rectificationReqText:
          type: string
          description: Testo con la richiesta di rettifica
          readOnly: true
        openNotes:
          type: string
          description: Note aperte studentessa o studente
          readOnly: true
      required:
        - rectificationId
        - state
        - date
        - rectificationReqText
        - openNotes
    DettaglioRettifica:
      type: object
      x-examples:
        Example 1:
          rectificationId: 6d183bc572f6b200015a4167
          enrollmentId: 908d3e72b51a6f0034e2a11c
          state: Accettata
          enrollmentToEnter:
            instituteCode: IFSRM1
            instituteName: Università degli Studi di Roma 'La Sapienza'
            courseType: Corso di laurea
            courseCode: INF101
            courseName: Ingegneria
            classCode: L-8
            className: Ingegneria informatica
            registrationYear: 2019/2020
            enrolmentYear: 2021/2022
            courseYear: 3° anno
          stateHistory:
            - state: Accettata
              date: '2023-06-10'
              description: Descrizione del passaggio di stato
            - state: In lavorazione
              date: '2023-03-05'
              description: Descrizione del passaggio di stato
            - state: Presa in carico
              date: '2023-02-25'
              description: Descrizione del passaggio di stato
          rectificationReqText: Testo con la richiesta di rettifica
          openNotes: Note aperte studentessa o studente
        Example 2:
          rectificationId: 6d183bc572f6b200015a4167
          enrollmentId: 908d3e72b51a6f0034e2a11c
          state: Accettata
          enrollmentToEdit:
            enrollmentId: 908d3e72b51a6f0034e2a11c
            fieldsToEdit:
              - fieldName: instituteName
                oldValue: Università degli studi di Milano
                newValue: Università degli studi di Roma 'La Sapienza'
              - fieldName: courseType
                oldValue: Laurea
                newValue: Corso di Laurea
              - fieldName: registrationYear
                oldValue: 2021/2022
                newValue: 2022/2023
              - fieldName: courseYear
                oldValue: 2° anno
                newValue: 3° anno
          stateHistory:
            - state: Accettata
              date: '2023-06-10'
              description: Descrizione del passaggio di stato
            - state: In lavorazione
              date: '2023-03-05'
              description: Descrizione del passaggio di stato
            - state: Presa in carico
              date: '2023-02-25'
              description: Descrizione del passaggio di stato
          rectificationReqText: Testo con la richiesta di rettifica
          openNotes: Note aperte dello studentessa o studente
      description: Dettaglio di una rettifica iscrizione per una studentessa o uno studente
      properties:
        rectificationId:
          type: string
          description: Identificativo della rettifica
          readOnly: true
        state:
          type: string
          description: stato attuale della rettifica
          readOnly: true
        enrollmentToEdit:
          $ref: '#/components/schemas/ModificaIscrizione'
        enrollmentToEnter:
          $ref: '#/components/schemas/Iscrizione'
        stateHistory:
          type: array
          description: Cronologia delle transizioni di stato
          items:
            $ref: '#/components/schemas/State'
        rectificationReqText:
          type: string
          description: Testo con la richiesta di rettifica
          readOnly: true
        openNotes:
          type: string
          description: Note aperte studente/ex studente
          readOnly: true
      required:
        - rectificationId
        - state
        - stateHistory
        - rectificationReqText
        - openNotes
    State:
      type: object
      properties:
        state:
          type: string
          description: valore dello stato
          readOnly: true
        date:
          type: string
          format: date
          description: data corrispondente alla transizione di stato
          readOnly: true
        description:
          type: string
          description: descrizione del passaggio di stato
          readOnly: true
      x-examples:
        Example 1:
          state: Accettata
          date: '2023-06-10'
          description: Descrizione del passaggio di stato
      description: Stato della Rettifica
  requestBodies: {}
  responses: {}
servers:
  - url: 'https://localhost:8080/api'
    description: localhost

