openapi: 3.0.0
info:
  title: | 
    IFS03 - Academic qualification degrees / Titoli accademici conseguiti
  x-summary: |
    Provides the detailed information regarding the academic qualification degrees got by the students at an university or AFAM / 
    Fornisce le informazioni di dettaglio riguardanti i titoli conseguiti da una studentessa o uno studente all'università o AFAM
  version: 2.1.0
  description: |
    Provides the detailed information regarding the academic qualification degrees got by the students at an university or AFAM / 
    Fornisce le informazioni di dettaglio riguardanti i titoli conseguiti da una studentessa o uno studente all'università o AFAM
  contact:
    name: Institute name
    email: formal.institute@email.it
  x-api-id: 00000000-0000-0000-0000-000000000000
  termsOfService: http://swagger.io/terms/'
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
paths:
  '/academic-qualifications':
    post:
      summary: | 
        Retrieve the details of academic qualifications got by a student. / 
        Acquisizione del dettaglio dei titoli accademici conseguiti da una studentessa/uno studente
      tags:
        - IFS03.1 - academic-qualifications
      security:
        - bearerAuth: []
      parameters: []
      responses:
        '200':
          description: Request successfully executed / Richiesta eseguita con successo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/academic_qualifications'
              examples:
                Personal_data only taxCode:
                  value:
                    personal_data:
                      tax_code: RSSMRA80A01F205D
                    qualifications:
                      - institute_code: '16'                      
                        qualification_name: Laurea in ingegneria informatica
                        programme_type_code: MS
                        degree_course_code: '1573960'
                        degree_class_code: MSLM32
                        academic_qualification_date: '2022-07-01'
                        qualification_grade_value: '110'
                        qualification_grading_scale_minimum_grade: 66
                        qualification_grading_scale_maximum_grade: 110
                Personal_data taxCode/personID:
                  value:
                    personal_data:
                      tax_code: RSSMRA80A01F205D
                      person_id: AB123456C      
                    qualifications:
                      - institute_code: '16'                       
                        qualification_name: Laurea in ingegneria informatica
                        programme_type_code: MS
                        degree_course_code: '1573960'
                        degree_class_code: MSLM32
                        academic_qualification_date: '2022-07-01'
                        qualification_grade_value: '110'
                        qualification_grading_scale_minimum_grade: 66
                        qualification_grading_scale_maximum_grade: 110
                Personal_data witout taxCode:
                  value:
                    personal_data:
                      given_name: Mario
                      family_name: Rossi
                      birth_date: 1980-01-01
                      birth_place: Italia,RM,Roma
                    qualifications:
                      - institute_code: '16'                      
                        qualification_name: Laurea in ingegneria informatica
                        programme_type_code: MS
                        degree_course_code: '1573960'
                        degree_class_code: MSLM32
                        academic_qualification_date: '2022-07-01'
                        qualification_grade_value: '110'
                        qualification_grading_scale_minimum_grade: 66
                        qualification_grading_scale_maximum_grade: 110
                Qualification 1:
                  value:
                    personal_data:
                      given_name: Mario
                      family_name: Rossi
                      birth_date: 1980-01-01
                      birth_place: Italia,RM,Roma
                    qualifications:
                      - institute_code: '16'                       
                        qualification_name: Laurea in ingegneria informatica
                        programme_type_code: MS
                        degree_course_code: '1573960'
                        degree_class_code: MSLM32
                        academic_qualification_date: '2022-07-01'
                        qualification_grade_value: '110'
                        qualification_grading_scale_minimum_grade: null
                        qualification_grading_scale_maximum_grade: null
                Qualification 2:
                  value:
                    personal_data:
                      given_name: Mario
                      family_name: Rossi
                      birth_date: 1980-01-01
                      birth_place: Italia,RM,Roma
                    qualifications:
                      - institute_code: '16'                        
                        qualification_name: Laurea in ingegneria informatica
                        programme_type_code: MS
                        degree_course_code: '1573960'
                        degree_class_code: MSLM32
                        academic_qualification_date: '2022-07-01'
                        qualification_grade_value: QUALIFIED
                        qualification_grading_scale_minimum_grade: null
                        qualification_grading_scale_maximum_grade: null        
        '400':
          description: <b>Bad Request</b> - il server non può elaborare la richiesta del client a causa di una sintassi errata o di una richiesta non valida. <br> Esempi di cause
            <br> - Richiesta non valida
            <br> - Sintassi errata
            <br> - Parametro mancante
            <br> - Richiesta incompleta
            <br> - ...               
        '500':
          description: Internal server error / Errore interno del server 
      operationId: academic-qualifications-of-student
      description: Returns the list of degrees earned by a student / Restituisce la lista dei titoli conseguiti da una studentessa o uno studente
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/it_qualification_request'
            examples:
              With tax_code/person_id:
                value:
                  tax_code: RSSMRA80A01F205D
                  person_id: 12345678A
              With key:
                value:
                  key: 8e44f796d7478a135c226598939d56a5b0d9405210235d4845ed158a7fec7535    
          application/xml:
            schema:
              type: object
              additionalProperties: false
              properties: {}
        description: 'Request di esempio, si rimanda al readme.md per le regole di obbligatorietà'
  '/proof-tertiary-education-qualifications':
    post:
      summary: | 
        Retrieve the evidences of the completion of tertiary education studies. / 
        Acquisizione delle prove riguardanti il completamento degli studi di istruzione terziaria
      tags:
        - IFS03.2 - proof-tertiary-education-qualifications
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Request successfully executed / Richiesta eseguita con successo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/proof_education_qualifications'
              examples:
                Statuscode=200:
                  value:
                    personal_data:
                      tax_code: RSSMRA80A01F205D
                      person_id: AB123456C
                    proof_qualifications:
                      - institute_code: '16'                        
                        qualification_name: Laurea in ingegneria informatica
                        programme_type_code: MS
                        programme_type_name: Laurea Magistrale (DM 270/04)
                        degree_course_code: '1573960'
                        degree_course_name: Ingegneria
                        degree_class_code: MSLM32
                        degree_class_name: Ingegneria informatica
                        academic_qualification_date: 2022-07-01
                        qualification_grade_value: '110'
                        qualification_grading_scale_minimum_grade: 66
                        qualification_grading_scale_maximum_grade: 110
                        academic_qualification_country: Italia
        '400':
          description: <b>Bad Request</b> - il server non può elaborare la richiesta del client a causa di una sintassi errata o di una richiesta non valida. <br> Esempi di cause
            <br> - Richiesta non valida
            <br> - Sintassi errata
            <br> - Parametro mancante
            <br> - Richiesta incompleta
            <br> - ...
        '500':
          description: Internal server error / Errore interno del server 
      operationId: Qualifications-education-of-student
      description: <ul> <li>Retrieves the evidences regarding completion of tertiary education studies (e.g. EQF levels 5/6/7/8)</li><li>Acquisisce le prove riguardanti il completamento degli studi di istruzione terziaria (ad esempio, livelli EQF 5/6/7/8)</li></ul>
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/eu_qualification_request'
            examples:
              Example:
                value:
                  tax_code: RSSMRA80A01F205D
                  person_id: 12345678A
          application/xml:
            schema:
              type: object
              additionalProperties: false
              properties: {}
        description: 'Request di esempio'
      parameters: []
  '/proof-tertiary-education-qualifications-level':

    post:
      summary: | 
        Retrieve the evidences of the qualification level of tertiary education studies. / 
        Acquisizione delle prove riguardanti il livello di qualifica degli studi di istruzione terziaria
      tags:
        - IFS03.3 - proof-tertiary-education-qualifications-level
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Request successfully executed / Richiesta eseguita con successo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/proof_education_qualifications_level'
              examples:
                Statuscode=200:
                  value:
                    personal_data:
                      tax_code: RSSMRA80A01F205D
                      person_id: AB123456C
                    proof_qualifications_level:
                      - qualification_name: Laurea in Ingegneria gestionale
                        degree_course_duration_in_months: 36
                        institute_code: '16'
                        institute_name: Milano - Politecnico
                        academic_qualification_date: 2022-07-01
                        total_ects: 180
                        eqf_level: 6° livello
                        nqf_level: I ciclo QF-EHEA
                        has_parent_relation: null
                        degree_course_duration_ects_credit: 180
                        ects_learnings: 
                          - learning_name: Analisi matematica I e Geometria
                            ects_credits: 10
                          - learning_name: Fisica sperimentale
                            ects_credits: 10
                          - learning_name: Fisica tecnica
                            ects_credits: 5
        '400':
          description: <b>Bad Request</b> - il server non può elaborare la richiesta del client a causa di una sintassi errata o di una richiesta non valida. <br> Esempi di cause
            <br> - Richiesta non valida
            <br> - Sintassi errata
            <br> - Parametro mancante
            <br> - Richiesta incompleta
            <br> - ...
        '500':
          description: Internal server error / Errore interno del server 
      operationId: Proof-tertiary-education-qualifications-level
      description:  <ul> <li>Rtrieves the evidences regarding the level of qualification of tertiary education studies, with the aim of facilitating the recognition of qualifications across borders, by providing information on NQF/EQF levels and their associated ECTS credits.</li><li>Acquisisce le prove riguardanti il livello di qualifica degli studi di istruzione terziaria, con l'obiettivo di agevolare il riconoscimento delle qualifiche oltre i confini, fornendo informazioni sui livelli NQF/EQF e i relativi crediti ECTS associati.</li></ul>
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/eu_qualification_request'
            examples:
              Example:
                value:
                  tax_code: RSSMRA80A01F205D
                  person_id: 12345678A
          application/xml:
            schema:
              type: object
              additionalProperties: false
              properties: {}
        description: 'Request di esempio'
      parameters: []
  '/proof-tertiary-education-qualifications-diploma-supplement':

    post:
      summary: | 
        Retrieve the evidences of the "Diploma Supplement". / 
        Acquisizione delle prove relative al "Diploma Supplement"
      tags:
        - IFS03.4 - proof-tertiary-education-qualifications-diploma-supplement
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Request successfully executed / Richiesta eseguita con successo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/proof_education_qualifications_diploma_supplement'
              examples:
                Statuscode=200:
                  value:
                    personal_data:
                      tax_code: RSSMRA80A01F205D
                      person_id: AB123456C
                    proof_qualifications_diploma_supplement:
                      - ects_credits_received: 180
                        institute_name: Cagliari - Università degli Studi
                        institute_code: '04'
                        programme_type_code: MS
                        programme_type_name: Laurea Magistrale (DM 270/04)
                        degree_course_code: '455'
                        degree_course_name: Ingegneria informatica
                        degree_class_code: MSLM32
                        degree_class_name: Ingegneria informatica
                        degree_course_duration_in_months: 36
                        qualification_grade_value: '100'
                        qualification_grading_scale_minimum_grade: 66
                        qualification_grading_scale_maximum_grade: 110
                        qualification_date: 2022-07-01
                        access_to_regulated_profession: Non applicabile
                        administering_institute_name: Cagliari - Università degli studi
                        administering_institute_status: public
                        qualification_institute_name: Cagliari - Università degli studi
                        qualification_institute_status: public
                        eqf_level: 6° livello
                        nqf_level: I ciclo QF-XXX
                        attended_learnings:
                          - learning_grade_value: '28'
                            learning_grading_scale_min: '18'
                            learning_grading_scale_max: '30'
                            learning_name: Analisi matematica I e Geometria
                            learning_start_date: '2018-12-01'
                            learning_end_date: '2019-03-01'
                            learning_cfu: 6
                          - learning_grade_value: '22'
                            learning_grading_scale_min: '18'
                            learning_grading_scale_max: '30'
                            learning_name: Fisica sperimentale
                            learning_start_date: '2018-06-01'
                            learning_end_date: '2018-10-01'
                            learning_cfu: 6
                          - learning_grade_value: QUALIFIED
                            learning_grading_scale_min: null
                            learning_grading_scale_max: null
                            learning_name: Fisica tecnica
                            learning_start_date: '2018-07-01'
                            learning_end_date: '2019-07-01'
                            learning_cfu: 6
                      
        '400':
          description: <b>Bad Request</b> - il server non può elaborare la richiesta del client a causa di una sintassi errata o di una richiesta non valida. <br> Esempi di cause
            <br> - Richiesta non valida
            <br> - Sintassi errata
            <br> - Parametro mancante
            <br> - Richiesta incompleta
            <br> - ...
        '500':
          description: Internal server error / Errore interno del server 
      description:  <ul> <li>Retrieves evidence relating to the "Diploma Supplement" developed jointly by the Council of Europe, the European Commission and UNESCO, and its updated version, adopted by the Lisbon Convention Committee in 2007</li><li>Recupera le prove relative allo strumento "Diploma Supplement," sviluppato congiuntamente dal Consiglio d'Europa, dalla Commissione Europea e dall'UNESCO, e della sua versione aggiornata, adottata dal Comitato della Convenzione di Lisbona nel 2007.</li></ul>
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/eu_qualification_request'
            examples:
              Example:
                value:
                  tax_code: RSSMRA80A01F205D
                  person_id: AB123456C
          application/xml:
            schema:
              type: object
              additionalProperties: false
              properties: {}
        description: 'Request di esempio'
      operationId: proof-tertiary-education-qualifications-diploma-supplement
      parameters: []

  /status:
    get:
      summary: Verifica stato delle API (Health Check)
      security: [{}]
      operationId: check-status
      description: Check the system's health status / Verificare lo stato di salute del sistema 
      tags:
        - health-check
      responses:
        '400':
          description: Bad Request
        '204':
          description: The service is running correctly / Il servizio è in esecuzione correttamente
        '500':
          description: The service is not running / Il servizio non è in esecuzione
components:
  headers:
    Retry-After:
      description: |-
        Retry contacting the endpoint *at least* after seconds.
        See https://tools.ietf.org/html/rfc7231#section-7.1.3
      schema:
        format: int32
        maximum: 186400
        minimum: 0
        type: integer
    X-RateLimit-Limit:
      description: The number of allowed requests in the current period
      schema:
        format: int32
        maximum: 1000000
        minimum: 0
        type: integer
    X-RateLimit-Remaining:
      description: The number of remaining requests in the current period
      schema:
        format: int32
        maximum: 1000000
        minimum: 0
        type: integer
    X-RateLimit-Reset:
      description: The number of seconds left in the current period
      schema:
        format: int32
        maximum: 186400
        minimum: 0
        type: integer
  schemas:
    academic_qualifications:
      type: object
      additionalProperties: false
      description: Registry and list of degrees earned by a student / Anagrafica ed elenco titoli conseguiti da una studentessa o uno studente
      properties:
        personal_data:
          $ref: '#/components/schemas/personal_data'
        qualifications:
          description: List of degrees earned by the student / Elenco dei titoli conseguiti dalla studentessa o dallo studente
          type: array
          maxItems: 256
          minItems: 0
          items:
            $ref: '#/components/schemas/qualifications'
    qualifications:
      type: object
      additionalProperties: false
      description: Degree detail / Dettaglio titolo
      properties:
        institute_code:
          type: string
          description: Institute identification code / Codice identificativo dell'istituto          
          minLength: 1
          maxLength: 256
          nullable: true
        qualification_name:
          type: string
          description: Title of the degree / Denominazione del titolo di studio          
          minLength: 1
          maxLength: 2048
          nullable: true
        programme_type_code:
          type: string
          description: Code of study program / codice del corso di studio
          example: 'LM'          
          minLength: 1
          maxLength: 256
        degree_course_code:
          type: string
          description: Course Code / Codice del corso          
          minLength: 1
          maxLength: 20
        degree_class_code:
          type: string
          description: Identification code of the degree class / Codice identificativo della classe di laurea
          example: MSLM32
          nullable: true
          minLength: 1
          maxLength: 20
        academic_qualification_date:
          type: string
          description: Date of graduation / Data di conseguimento del titolo di studio
          pattern: '^[0-9]{4}-[0-9]{2}-[0-9]{2}$'
          example: '2023-05-15'
          format: date          
        qualification_grade_value:
          type: string
          description: Grade obtained upon graduation / Voto ottenuto al conseguimento del titolo di studio
          minLength: 1
          maxLength: 32
          example: '110'
          pattern: ^(\d+(.\d{1,2})?|\d+L|QUALIFIED)$
          nullable: true
        qualification_grading_scale_minimum_grade:
          type: number
          format: float
          minimum: 0
          maximum: 9999
          example: 66
          description: Minimum course grade / Voto minimo del corso
          nullable: true
        qualification_grading_scale_maximum_grade:
          type: number
          format: float
          minimum: 0
          maximum: 9999
          nullable: true
          example: 110
          description: Highest course grade / Voto massimo del corso
      required:
        - institute_code
        - programme_type_code
        - degree_course_code
        - academic_qualification_date
        - qualification_grade_value
    proof_education_qualifications:
      additionalProperties: false
      type: object
      description: Qualification details of student / Dettaglio titoli di una studentessa o di uno studente
      properties:
        personal_data:
          $ref: '#/components/schemas/personal_data'
        proof_qualifications:
          type: array
          maxItems: 256
          minItems: 0
          description: List of qualifications for student / Elenco titoli di una studentessa o di uno studente
          items:
            $ref: '#/components/schemas/proof_qualifications'
      required:
        - personal_data
        - proof_qualifications
    proof_qualifications:
      type: object
      additionalProperties: false
      description: Detailed qualification information / Informazioni dettagliate sul titolo
      properties:
        institute_code:
          type: string
          description: Institute identification code / Codice identificativo dell’istituto
          example: '16'          
          minLength: 1
          maxLength: 256
          nullable: true
        institute_name:
          type: string
          description:  Institute's name / Denominazione dell’istituto
          example: 'Milano - Politecnico'          
          minLength: 1
          maxLength: 2048
          nullable: true
        qualification_name:
          type: string
          description: Name qualification achieved / Nome titolo ottenuto
          example: 'Laurea in ingegneria informatica'          
          minLength: 1
          maxLength: 2048
          nullable: true
        programme_type_code:
          type: string
          description: Code of study program / codice del corso di studio
          example: 'LM'
          minLength: 1
          maxLength: 256
          nullable: true
        programme_type_name:
          type: string
          description: Type of course of study / Tipo di corso di studio
          example: 'Laurea Specialistica (DM 509/99), Laurea Magistrale (DM 270/04), Laurea Triennale (DM 509/99)'
          minLength: 1
          maxLength: 2048
          nullable: true
        degree_course_code:
          type: string
          description: Course Code / Codice del corso
          minLength: 1
          maxLength: 20
          nullable: true
        degree_course_name:
          type: string
          description: Course name / Denominazione corso
          example: 'ingegneria, economia, giurisprudenza, medicina, scienze umanistiche, scienze sociali, informatica, arte e design'
          minLength: 1
          maxLength: 2048
          nullable: true
        degree_class_code:
          type: string
          description: Identification code of the degree class / Codice identificativo della classe di laurea
          example: MSLM32
          nullable: true
          minLength: 1
          maxLength: 20
        degree_class_name:
          type: string
          description: Name of the degree class / Denominazione della classe di laurea 
          example: 'Informatica, Meccanica, Elettronica, Civile'
          minLength: 1
          maxLength: 2048
          nullable: true
        academic_qualification_date:
          type: string
          format: date
          description: Date of completion of studies / Data completamento studi
          example: 2023-10-01
          nullable: true
        qualification_grade_value:
          type: string
          description: Grade / voto
          minLength: 1
          maxLength: 32
          example: '110'
          pattern: ^(\d+(.\d{1,2})?|\d+L|QUALIFIED|[A-Z])$
          nullable: true
        qualification_grading_scale_minimum_grade:
          type: number
          format: float
          minimum: 0
          maximum: 9999
          nullable: true
          example: 66
          description: Minimum course grade / Voto minimo del corso    
        qualification_grading_scale_maximum_grade:
          type: number
          format: float
          minimum: 0
          maximum: 9999
          nullable: true
          example: 110
          description: Highest course grade / Voto massimo del corso
        academic_qualification_country:
          type: string
          description: Country where it has got the academic qualification / Paese dove è stato conseguito il titolo
          example: Italia      
          minLength: 1
          maxLength: 2048
          nullable: true
    proof_education_qualifications_diploma_supplement:
      additionalProperties: false
      type: object
      description: Returns the list of simplified supplment diplomas in SDG format / Restituisce la lista dei diplomi supplment semplificati in formato SDG
      properties:
        personal_data:
          $ref: '#/components/schemas/personal_data'
        proof_qualifications_diploma_supplement:
          type: array
          minItems: 0
          items:
            $ref: '#/components/schemas/proof_qualification_diploma_supplement'
      required:
        - personal_data
        - proof_qualifications_diploma_supplement
    proof_education_qualifications_level:
      additionalProperties: false
      type: object
      description: Returns the list of simplified supplment diplomas in SDG format / Restituisce la lista dei diplomi supplment semplificati in formato SDG
      properties:
        personal_data:
          $ref: '#/components/schemas/personal_data'
        proof_qualifications_level:
          type: array
          minItems: 0
          items:
            $ref: '#/components/schemas/proof_qualification_level'
      required:
        - personal_data
        - proof_qualifications_level
    proof_qualification_diploma_supplement:
      type: object
      additionalProperties: false
      description: Simplified supplment diplomas in SDG format / Diplomi supplment semplificati in formato SDG
      properties:
        ects_credits_received:
          format: int32
          type: integer
          description: Credits recieved / Crediti ricevuti
          example: 180
          maximum: 999
          minimum: 1
          nullable: true
        institute_name: 
          type: string
          description: Institute name / Nome dell'istituto
          example: 'Cagliari - Università degli Studi'
          minLength: 1
          maxLength: 2048
          nullable: true
        institute_code:
          type: string
          description: Institute identification code / Codice identificativo dell’istituto
          example: '04'
          minLength: 1
          maxLength: 256
          nullable: true
        programme_type_code:
          type: string
          description: Code of study program / codice del corso di studio
          example: 'MS'
          minLength: 1
          maxLength: 256
          nullable: true
        programme_type_name:
          type: string
          description: Type of course of study / Tipo di corso di studio
          example: 'Laurea Magistrale (DM 270/04)'
          minLength: 1
          maxLength: 2048
          nullable: true
        degree_course_code:
          type: string
          description: Course Code / Codice del corso
          example: '455'
          minLength: 1
          maxLength: 20
          nullable: true
        degree_course_name:
          type: string
          description: Course name / Denominazione corso
          example: 'Ingegneria informatica'
          minLength: 1
          maxLength: 2048
          nullable: true
        degree_class_code:
          type: string
          description: Identification code of the degree class / Codice identificativo della classe di laurea
          example: MSLM32
          nullable: true
          minLength: 1
          maxLength: 20
        degree_class_name:
          type: string
          description: Name of the degree class / Denominazione della classe di laurea 
          example: 'Ingegneria informatica'
          minLength: 1
          maxLength: 2048
          nullable: true
        degree_course_duration_in_months:
          type: integer
          format: int32
          description: Duration of ccourse / Durata del corso
          example: 36
          minimum: 0
          maximum: 999
          nullable: true
        qualification_grade_value:
          type: string
          description: Grade / voto
          example: '100'          
          minLength: 1
          maxLength: 32
          pattern: ^(\d+(.\d{1,2})?|\d+L|QUALIFIED)$
          nullable: true
        qualification_grading_scale_minimum_grade:
          type: number
          format: float
          minimum: 0
          maximum: 9999
          description: Rating scale minimum / Scala di valutazione minima
          example: 66         
          nullable: true
        qualification_grading_scale_maximum_grade:
          type: number
          format: float
          minimum: 0
          maximum: 9999
          description: Rating scale maximum / Scala di valutazione massima
          example: 110          
          nullable: true
        qualification_date:
          type: string
          format: date
          description: Date of completion of studies / Data completamento studi
          example: 2022-07-01          
          nullable: true
        access_to_regulated_profession:
          type: string
          description: Rating scale maximum / Scala di valutazione massima
          example: 'Non applicabile'          
          minLength: 1
          maxLength: 32
          nullable: true
        administering_institute_name:
          type: string
          description: Administering institute name / Nome dell'Istituto Amministratrice
          example: 'Cagliari - Università degli studi'          
          minLength: 1
          maxLength: 2048
          nullable: true
        administering_institute_status:
          type: string
          description: Administering institute status / Stato dell'Istituto Amministratrice
          example: 'public'          
          enum: 
            - public
            - private
          nullable: true
        qualification_institute_name:
          type: string
          description: Qualiification institute name / Nome dell'Istituto di qualificazione
          example: 'Cagliari - Università degli studi'          
          minLength: 1
          maxLength: 2048
          nullable: true
        qualification_institute_status:
          type: string
          description: Qualiification institute status / Stato dell'Istituto di qualificazione
          example: 'public'          
          enum:
            - private
            - public
          nullable: true
        eqf_level:
          type: string
          description: EQF level / Livello EQF
          example: '6° livello'          
          minLength: 1
          maxLength: 2048
          nullable: true
        nqf_level:
          type: string
          description: NQF level / Livello NQF
          example: 'I ciclo QF-XXX'
          minLength: 1
          maxLength: 2048
          nullable: true
        attended_learnings:
          type: array
          maxItems: 256
          minItems: 0
          description: List of attended learnings / Elenco corsi frequentati
          items:
            $ref: '#/components/schemas/attended_learnings'
          nullable: true
    proof_qualification_level:
      type: object
      additionalProperties: false
      description: Simplified supplment diplomas in SDG format / Diplomi supplment semplificati in formato SDG
      properties:
        qualification_name:
          type: string
          description: Diploma name / Denominazione diploma
          example: 'Laurea in Scienze Aziendali'
          minLength: 1
          maxLength: 2048
          nullable: true
        degree_course_duration_in_months:
          type: integer
          format: int32
          description: Duration of study programme in months / Durata programma di studio in mesi
          example: 36
          minimum: 0
          maximum: 999
          nullable: true
        institute_code:
          type: string
          description: Institute identification code / Codice identificativo dell’istituto
          example: '16'
          minLength: 1
          maxLength: 256
          nullable: true
        institute_name:
          type: string
          description: Institute's name / Denominazione dell’istituto
          example: 'Milano - Politecnico'
          minLength: 1
          maxLength: 2048
          nullable: true
        academic_qualification_date:
          type: string
          format: date
          description: Date of graduation / Data ottenimento titolo
          example: 2022-07-01
          nullable: true
        total_ects:
          type: integer
          format: int32
          description: Total ECTS credits / Crediti totali ECTS
          example: 180
          maximum: 999
          minimum: 1
          nullable: true
        eqf_level:
          type: string
          description: EQF level / Livello EQF
          example: '6° livello'
          minLength: 1
          maxLength: 2048
          nullable: true
        nqf_level:
          type: string
          description: NQF level / Livello NQF
          example: 'I ciclo QF-EHEA'
          minLength: 1
          maxLength: 2048
          nullable: true
        has_parent_relation:
          type: boolean
          nullable: true
          description: Parent relation / Relazione con i genitori
          example: true
        degree_course_duration_ects_credit:
          type: integer
          format: int32
          description: Course duration in ECTS / Durata corso di studi in ECTS
          example: 180
          maximum: 999
          minimum: 1
          nullable: true
        ects_learnings:
          type: array
          nullable: true
          maxItems: 256
          minItems: 0
          description: List of courses in ECTS / Elenco corsi in ECTS
          items:
            $ref: '#/components/schemas/ects_learnings'
    attended_learnings:
      type: object
      additionalProperties: false
      description: Detailed information on completed courses / Informazioni dettagliate sui corsi completati
      properties:
        learning_cfu:
          type: integer
          format: int32
          description: Learning CFU / CFU insegnamento
          example: 10          
          minimum: 1
          maximum: 999
          nullable: true
        learning_grade_value:
          type: string
          description: Exam vote / Voto d'esame
          example: '30'          
          pattern: ^(\d+(.\d{1,2})?|\d+L|QUALIFIED|[A-Z])$
          nullable: true
        learning_grading_scale_min:
          type: string
          description: minimun Exam vote / Voto d'esame minimo
          example: '18'
          pattern: ^(\d+(.\d{1,2})?|[A-Z])$             
          nullable: true
        learning_grading_scale_max:
          type: string
          description: Exam vote / Voto d'esame massimo
          example: '30'
          pattern: ^(\d+(.\d{1,2})?|[A-Z])$     
          nullable: true
        learning_name:
          type: string
          description: Exam name / Nome d'esame
          example: 'Esame 1, Esame 2'          
          minLength: 1
          maxLength: 2048
          nullable: true
        learning_start_date:          
          type: string
          description: Course start date / Data inizio corso
          example: 2018-12-01          
          minLength: 10
          maxLength: 10
          nullable: true
        learning_end_date:          
          type: string
          format: date
          description: Course end date / Data fine corso
          example: 2019-03-01          
          nullable: true
    ects_learnings:
      type: object
      additionalProperties: false
      description: Detailed information on ECTS courses / Informazioni dettagliate sui corsi in ECTS
      properties:
        learning_name:
          type: string
          description: Learning name / Nome insegnamento
          example: Fisica tecnica
          minLength: 1
          maxLength: 2048
        ects_credits:
          type: integer
          format: int32
          description: Course in ECTS / Corso in ECTS
          example: 180
          maximum: 999
          minimum: 1
      required:
        - learning_name
        - ects_credits 
    personal_data:
      type: object
      additionalProperties: false
      description: Personal data of the student / Dati personali della studentessa o dello studente
      properties:
        tax_code:
          type: string
          description: Tax Identification Number / Codice Fiscale
          example: RSSMRA80A01F205D
          pattern: '^(?:^(?:[A-Z][AEIOU][AEIOUX]|[B-DF-HJ-NP-TV-Z]{2}[A-Z]){2}(?:[\dLMNP-V]{2}(?:[A-EHLMPR-T](?:[04LQ][1-9MNP-V]|[15MR][\dLMNP-V]|[26NS][0-8LMNP-U])|[DHPS][37PT][0L]|[ACELMRT][37PT][01LM]|[AC-EHLMPR-T][26NS][9V])|(?:[02468LNQSU][048LQU]|[13579MPRTV][26NS])B[26NS][9V])(?:[A-MZ][1-9MNP-V][\dLMNP-V]{2}|[A-M][0L](?:[1-9MNP-V][\dLMNP-V]|[0L][1-9MNP-V]))[A-Z]$)'
          minLength: 16
          maxLength: 16
          nullable: true
        person_id:
          type: string
          description: Unique National Identifier (ANPR ID) / Identificativo unico nazionale (ID ANPR) 
          maxLength: 9
          minLength: 9
          pattern: "^[A-Z0-9]{9}$"
          example: AB123456C
          nullable: true
        given_name:
          type: string
          description: Name / Nome
          example: Mario
          pattern: ^[\p{L}'’\- ]+$
          minLength: 1
          maxLength: 2048
          nullable: true
        family_name:
          type: string
          description: Surname / Cognome
          example: Rossi
          pattern: ^[\p{L}'’\- ]+$
          minLength: 1
          maxLength: 2048
          nullable: true
        birth_date:
          type: string
          format: date
          example: '1990-05-17'
          pattern: '^\d{4}-\d{2}-\d{2}$'
          description: Date of birth / Data di nascita
          nullable: true
        birth_place:
          type: string
          example: Italia,RM,Roma
          description: Place of birth / Luogo di nascita
          minLength: 1
          maxLength: 2048
          nullable: true
          pattern: .*,[a-zA-Z]*,[a-zA-Z]*

    it_qualification_request:
      type: object
      additionalProperties: false      
      description: Request qualifications of a student's  / Richiesta titoli di una studentessa o uno studente
      properties:
        tax_code:
          type: string
          description: Tax Identification Number / Codice fiscale
          pattern: '^(?:^(?:[A-Z][AEIOU][AEIOUX]|[B-DF-HJ-NP-TV-Z]{2}[A-Z]){2}(?:[\dLMNP-V]{2}(?:[A-EHLMPR-T](?:[04LQ][1-9MNP-V]|[15MR][\dLMNP-V]|[26NS][0-8LMNP-U])|[DHPS][37PT][0L]|[ACELMRT][37PT][01LM]|[AC-EHLMPR-T][26NS][9V])|(?:[02468LNQSU][048LQU]|[13579MPRTV][26NS])B[26NS][9V])(?:[A-MZ][1-9MNP-V][\dLMNP-V]{2}|[A-M][0L](?:[1-9MNP-V][\dLMNP-V]|[0L][1-9MNP-V]))[A-Z]$)'
          example: RSSMRA80A01F205D
          minLength: 16
          maxLength: 16
        person_id:
          type: string
          description: Unique National Identifier (ANPR ID) / Identificativo unico nazionale (ID ANPR) 
          maxLength: 9
          minLength: 9
          pattern: "^[A-Z0-9]{9}$"
          example: AB123456C
          nullable: true
        key:
          type: string
          description: Hash tax code / Hash del codice fiscale
          example: 8e44f796d7478a135c226598939d56a5b0d9405210235d4845ed158a7fec7535
          minLength: 64
          maxLength: 64
        institute_code:
          type: string
          description: Institute identification code / Codice identificativo dell’istituto
          example: AA
          minLength: 1
          maxLength: 256
          nullable: true   
    eu_qualification_request:
      type: object
      additionalProperties: false      
      description: Request qualifications of a student's  / Richiesta titoli di una studentessa o uno studente
      properties:
        tax_code:
          type: string
          description: Tax Identification Number / Codice fiscale
          pattern: '^(?:^(?:[A-Z][AEIOU][AEIOUX]|[B-DF-HJ-NP-TV-Z]{2}[A-Z]){2}(?:[\dLMNP-V]{2}(?:[A-EHLMPR-T](?:[04LQ][1-9MNP-V]|[15MR][\dLMNP-V]|[26NS][0-8LMNP-U])|[DHPS][37PT][0L]|[ACELMRT][37PT][01LM]|[AC-EHLMPR-T][26NS][9V])|(?:[02468LNQSU][048LQU]|[13579MPRTV][26NS])B[26NS][9V])(?:[A-MZ][1-9MNP-V][\dLMNP-V]{2}|[A-M][0L](?:[1-9MNP-V][\dLMNP-V]|[0L][1-9MNP-V]))[A-Z]$)'
          example: RSSMRA80A01F205D
          minLength: 16
          maxLength: 16
        person_id:
          type: string
          description: Unique National Identifier (ANPR ID) / Identificativo unico nazionale (ID ANPR) 
          maxLength: 9
          minLength: 9
          pattern: "^[A-Z0-9]{9}$"
          example: AB123456C
          nullable: true
      required:
        - tax_code
  requestBodies: {}
  responses: {}
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: PASETO 
servers:
  - url: 'https://localhost:8080/api'
    description: localhost
tags:
  - name: IFS03.1 - academic-qualifications
  - name: IFS03.2 - proof-tertiary-education-qualifications
  - name: IFS03.3 - proof-tertiary-education-qualifications-level
  - name: IFS03.4 - proof-tertiary-education-qualifications-diploma-supplement
  - name: health-check