openapi: 3.0.0
info:
  title: IFS07 - Changes in academic qualifications / Variazioni nei titoli accademici
  x-summary: |
    Retrieve the changes in academic qualifications / Ottiene le variazioni dei titoli accademici
  version: 1.0.0
  description: |
    Retrieve the changes in academic qualifications / Ottiene le variazioni dei titoli accademici
  contact:
    name: helpdesk
    email: helpdesk@gmail.com
  x-api-id: 00000000-0000-0000-0000-000000000000
  termsOfService: 'http://swagger.io/terms/'
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
paths:
  '/student-qualifications-changes':
    post:
      summary: | 
        Retrieve the "fingerprints (hash codes)" of all students' academic qualifications to identify the changes from the recipient's perspective. / 
        Acquisizione delle "impronte (codifica hash)" dei titoli accademici di tutti gli studenti al fine di identificarne le variazioni dal punto di vista del fruitore
      tags:
        - IFS07.1 - student-qualifications-changes
      security: [{}]
      responses:
        '200':
          description: Request successfully executed / Richiesta eseguita con successo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/student-qualifications-changes'
              examples:
                Exist a next page (cursor is valued):
                  value:
                    data:
                      institute_code: C6
                      last_update: '2023-10-13T17:32:28Z'
                      qualifications_hash:
                        - key: '8e44f796d7478a135c226598939d56a5b0d9405210235d4845ed158a7fec7535'
                          hash: '56c3880bfcc4df0e35780c805d9ec942bbb8b4e237c1b63c6f2688cb58ef0a3a'
                        - key: 'p9sndsh75636d7478a135c226598939d56a5b0d94052102oiasdh7632bbc78h843'
                          hash: '56c3880bfcc4df0e35780c80sdlkjljiirpepw85830t3j85jg0fj054fj04jf03'
                        - key: 'qmane9vsd7cksad8e44f796d7478a135c226598939d56a5b0d94052102gh9msabv9s'
                          hash: 'df8340f834tr8f3j84fj48jf83fngooero45305jf30l04k0r43kfd043kdew34t'
                    meta:
                      cursor: '6eyJpZCI6M57'
                The last page (cursor is not valued):
                  value:
                    data:
                      institute_code: C6
                      last_update: '2023-10-13T17:32:28Z'
                      qualifications_hash:
                        - key: '8e44f796d7478a135c226598939d56a5b0d9405210235d4845ed158a7fec7535'
                          hash: '56c3880bfcc4df0e35780c805d9ec942bbb8b4e237c1b63c6f2688cb58ef0a3a'
                        - key: 'p9sndsh75636d7478a135c226598939d56a5b0d94052102oiasdh7632bbc78h843'
                          hash: '56c3880bfcc4df0e35780c80sdlkjljiirpepw85830t3j85jg0fj054fj04jf03'
                        - key: 'qmane9vsd7cksad8e44f796d7478a135c226598939d56a5b0d94052102gh9msabv9s'
                          hash: 'df8340f834tr8f3j84fj48jf83fngooero45305jf30l04k0r43kfd043kdew34t'
                    meta:
                      cursor: null     
        '400':
          description: <b>Bad Request</b> - il server non può elaborare la richiesta del client a causa di una sintassi errata o di una richiesta non valida. <br> Esempi di cause
            <br> - Richiesta non valida
            <br> - Sintassi errata
            <br> - Parametro mancante
            <br> - Richiesta incompleta
            <br> - ...
        '500':
          description: Internal server error / Errore interno del server 
      
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/student_qualifications_changes_request'
            examples:
              call with cursor:
                value:
                  cursor: fowfio543s
                  institute_code: AA     
                  university_system_type: new
                  sync_mode: full
          application/xml:
            schema:
              type: object
              additionalProperties: false
              properties: {}
      description: Returning the information reduced to a 'hash (SHA256)' for each student in the form (key, value), where the key is the hash of the student's social security number and the value is the hash of the student's qualifications. / Restituisce le informazioni ridotte in "hash (SHA256)" per ogni studente/studentessa nella forma (chiave, valore), dove la chiave è l'hash del codice fiscale dello studente e il valore è l'hash dei suoi titoli.
      parameters: []
  /status:
    get:
      summary: Verifica stato delle API (Health Check)
      security: [{}]
      operationId: check-status
      description: Check the system's health status / Verificare lo stato di salute del sistema 
      tags:
        - health-check
      responses:
        '400':
          description: Bad Request
        '204':
          description: The service is running correctly / Il servizio è in esecuzione correttamente
        '500':
          description:  The service is not running. / Il servizio non è in esecuzione. 
components:
  headers:
    Retry-After:
      description: |-
        Retry contacting the endpoint *at least* after seconds.
        See https://tools.ietf.org/html/rfc7231#section-7.1.3
      schema:
        format: int32
        maximum: 186400
        minimum: 0
        type: integer
    X-RateLimit-Limit:
      description: The number of allowed requests in the current period / Numero di richieste consentite nel periodo attuale
      schema:
        format: int32
        maximum: 1000000
        minimum: 0
        type: integer
    X-RateLimit-Remaining:
      description: The number of remaining requests in the current period / Numero di richieste rimanenti nel periodo attuale 
      schema:
        format: int32
        maximum: 1000000
        minimum: 0
        type: integer
    X-RateLimit-Reset:
      description: The number of seconds left in the current period / Numero di secondi rimanenti nel periodo attuale
      schema:
        format: int32
        maximum: 186400
        minimum: 0
        type: integer
  schemas:
    student_qualifications_changes_request:
      type: object
      additionalProperties: false
      description: ''
      properties:
        cursor:
          type: string
          description: |
            Cursor / Cursore
            Indica il valore del cursore restituito dalla chiamata.
            * Da NON valorizzare durante la prima invocazione;
            * Da valorizzare nelle invocazioni successive (laddove presente))
          example: 'fowfio543s'
          nullable: true
          minLength: 1
          maxLength: 512
        institute_code:
          type: string
          description: Institute identification code / Codice identificativo dell’istituto  
          example: 'AA'          
          minLength: 1
          maxLength: 256
          nullable: true
        university_system_type:
          type: string
          description: |
            1. The value 'old' refers to all academic degrees obtained before the University/AFAM system regulated by law decree 509/99 for the University and 508/99 for the AFAM. 
            2. The value 'new' refers to academic degrees obtained since the University/AFAM system regulated by law decree 509/99 for the University and 508/99 for the AFAM.
            3. If this parameter is not specified, the API returns academic degrees from both the old and new University systems.
            > 
            1. Il valore 'old' si riferisce a tutti i titoli accademici ottenuti prima del nuovo ordinamento Universitario/AFAM regolato dai decreti legislativi 509/99 per l'Università e 508/99 per l'AFAM.
            2. Il valore 'new' si riferisce ai titoli accademici ottenuti a partire dal nuovo oridnamento Universitario/AFAM regolato dai decreti legislativi 509/99 per l'Università e 508/99 per l'AFAM.
            3. Se questo parametro non è specificato, l'API restituisce i titoli accademici sia del vecchio che del nuovo ordinamento.
          example: 'new'          
          minLength: 1
          maxLength: 256
          nullable: false
          enum:
            - old
            - new
        sync_mode:
          type: string
          description: | 
            1.	The value 'full' represents all academic degrees
            2.	The value 'incremental' represents:
              a) Every academic qualification obtained by the student in the past 2 calendar years  (based on the qualification date).
              b) Any academic degree modified in the past 2 calendar years (based on the degree change date). If a student no longer has any academic degree because it was deleted, the API returns either null or a hash of a null entity.
            3.  If this parameter isn't valorized the default value is **full**
            >
            1. Il valore 'full' rappresenta tutti i titoli accademici
            2. Il valore 'incremental' rappresenta:
              a) Ogni qualifica accademica ottenuta dallo studente negli ultimi 2 anni solari (basata sulla data di conseguimento del titolo).
              b) Qualsiasi titolo accademico rettificato negli ultimi 2 anni solari (basato sulla data di rettifica del titolo). Se uno studente non ha più alcun titolo accademico perché è stato eliminato, l'API restituisce null o un hash di un'entità null.
            3. Se questo parametro non è valorizzato, il valore predefinito è **full**
          example: 'full'          
          minLength: 1
          maxLength: 256
          nullable: true  
          enum:
            - incremental
            - full
      required:
        - cursor
        - institute_code
        - university_system_type
        - sync_mode
    student-qualifications-changes:
      additionalProperties: false
      type: object
      description: Returning the information reduced to a 'hash (SHA256)' for each student in the form (key, value), where the key is the hash of the student's social security number and the value is the hash of the student's qualifications. / Restituisce le informazioni ridotte in "hash (SHA256)" per ogni studente/studentessa nella forma (chiave, valore), dove la chiave è l'hash del codice fiscale dello studente e il valore è l'hash dei suoi titoli.
      properties:
        data:
          $ref: '#/components/schemas/data'
        meta:
            $ref: '#/components/schemas/meta'
      required:
        - data
        - meta
    meta:
      type: object
      additionalProperties: false
      nullable: true
      description: Informazioni del cursore
      properties:
        cursor:
          type: string
          description: Cursor / Cursore
          example: 'fowfio543s'          
          minLength: 1
          maxLength: 512
          nullable: true
    data:
      type: object
      additionalProperties: false
      description: Personal data of the student / Dati personali della studentessa o dello studente
      properties:
        institute_code:
          type: string
          description: Institute identification code / Codice identificativo dell’istituto
          example: 'C3'          
          minLength: 1
          maxLength: 256
          nullable: true
        last_update:
          type: string
          format: date-time
          description: Date of last update / Data ultimo aggiornamento
          example: '2023-10-13T17:32:28Z'
        qualifications_hash:
          type: array
          minItems: 0
          description: List of qualifications for student / Elenco iscrizioni di una studentessa o di uno studente
          items:
            $ref: '#/components/schemas/qualifications_hash'
    qualifications_hash:
      type: object
      additionalProperties: false
      description: Detailed qualification information / Informazioni dettagliate sul titoli
      properties:
        key:
          type: string
          description: Hash tax code / Hash del codice fiscale
          example: '8e44f796d7478a135c226598939d56a5b0d9405210235d4845ed158a7fec7535'
          minLength: 64
          maxLength: 64
        hash:
          type: string
          description: Enrollments hash code / Codice hash delle iscrizioni
          example: '9bc4e295f51d940db6d7a9ca01059ace00376d4feed10225c592e010a780a8d5'
          minLength: 64
          maxLength: 64
      required:
        - key
        - hash
  requestBodies: {}
  responses: {}
servers:
  - url: 'https://localhost:8080/api'
    description: localhost
tags:
  - name: IFS07.1 - student-qualifications-changes
  - name: health-check