openapi: 3.0.0
info:
  title: IFS01 - Educational offer / Offerta formativa 
  x-summary: Acquire data on the courses active and offered by an institute in a given academic year. / Vuole acquisire i dati dei corsi attivi ed offerti da un Istituto in un dato anno accademico.
  version: 2.0.6-rc
  description: |
    Obtains the list of courses provided by a public university or AFAM. The data returned includes information on the individual courses offered. / Ottiene l'elenco dei corsi erogati da un'università o AFAM pubblica. I dati restituiti includono informazioni sui singoli corsi offerti.
  contact:
    name: helpdesk
    email: helpdesk@gmail.com
  x-api-id: 00000000-0000-0000-0000-000000000000
  termsOfService: http://swagger.io/terms/
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
paths:
  '/educational-offering-list': 
    post:
      summary: > 
        Retrieve the list of study programs offered by a tertiary education institute in a given academic year. / 
        Acquisizione della lista dei corsi di studio offerti da un Istituto di fomrazione superiore in un dato anno accademico.
      tags:
        - IFS01.1 - educational-offering-list
      security: 
        - bearerAuth: []
      responses:
        '200':
          description: Request successfully executed / Richiesta eseguita con successo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/course_list'
              examples:
                Università:
                  value:
                    degree_courses:
                      - programme_type_code: LT
                        programme_access: free
                        course_location: '015146'
                        course_area: Ingegneria industriale
                        degree_course_language: IT
                        degree_course_period_years: 3
                        degree_course_code: '353'
                        total_credits: 180
                        academic_year: 2023/2024
                      - programme_type_code: MS
                        programme_access: free
                        course_location: 015146,015211
                        course_area: Ingegneria aerospaziale e astronautica
                        degree_course_language: EN
                        degree_course_period_years: 2
                        degree_course_code: '469'
                        total_credits: 120
                        academic_year: 2023/2024
                    meta:
                      cursor: '6eyJpZCI6M57'
                AFAM:
                  value:
                    degree_courses:
                      - programme_type_code: LT
                        programme_access: free
                        course_location: '058091'
                        course_area: DISCIPLINE INTERPRETATIVE
                        degree_course_language: IT
                        degree_course_period_years: 3
                        degree_course_code: '1234'
                        total_credits: 180
                        academic_year: 2023/2024
                      - programme_type_code: XX
                        programme_access: free
                        course_location: 058091,058039
                        course_area: DISCIPLINE INTERPRETATIVE
                        degree_course_language: EN
                        degree_course_period_years: 2
                        degree_course_code: '5678'
                        total_credits: 120
                        academic_year: 2023/2024
                      - programme_type_code: YY
                        programme_access: free
                        course_location: 058091,058039
                        course_area: Discipline interpretative del jazz, delle musiche improvvisate e audiotattili
                        degree_course_language: EN
                        degree_course_period_years: 2
                        degree_course_code: '9565'
                        total_credits: 120
                        academic_year: 2023/2024 
                    meta:
                      cursor: '6eyJpZCI6M57'
        '400':
          description: <b>Bad Request</b> - il server non può elaborare la richiesta del client a causa di una sintassi errata o di una richiesta non valida. <br> Esempi di cause
            <br> - Richiesta non valida
            <br> - Sintassi errata
            <br> - Parametro mancante
            <br> - Richiesta incompleta
            <br> - ...
        '500':
          description: Internal server error / Errore interno del server 
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/course_list_request'
            examples:
              1 - prima invocazione:
                value:
                  academic_year: 2023/2024              
              2 - invocazioni successive alla prima:
                value:
                  academic_year: 2023/2024
                  cursor: "abc123456abc"      
          application/xml:
            schema:
              type: object
              additionalProperties: false
              properties: {}
        description: "PUNTO DI ATTENZIONE:\n  * NON valorizzare l'attributo cursor durante la prima invocazione;\n\ * Valorizzare l'attributo cursor nelle invocazioni successive (laddove presente nella precedente Response);"
      
      operationId: educational-offering-list
      description: <ul> <li>Request the list of active courses offered by the Institute in an academic year. </li><li>Richiedi la lista dei corsi attivi offerti dall'Istituto in un anno accademico.</li></ul>
      parameters: []
  '/educational-offering-detail': 
    post:
      summary: |
        Retrieve the details of a study program offered by a tertiary education institute. 
        It's enough to reply with only the first year course of the study program refered by the 
        course degree input parameter / Acquisizione del dettaglio di un corso di studio offerto da un istituto 
        di formazione superiore. E' sufficente includere il solo primo anno di corso dell’offerta disponibile 
        per la coorte relativa al codice corso inviato come parametro di ingresso nella richiesta.
      tags:
        - IFS01.2 - educational-offering-detail
      security: 
        - bearerAuth: []
      responses:
        '200':
          description: Request successfully executed / Richiesta eseguita con successo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/course_details'
              examples:
                AFAM:
                  value:
                      programme_type_code: LT
                      programme_access: free
                      course_location: '058091'
                      remote_mode: on-site
                      course_area: DISCIPLINE INTERPRETATIVE
                      degree_course_language: IT
                      degree_course_period_years: 3
                      degree_course_code: '1234'
                      total_credits: 180
                      academic_year: 2023/2024
                      first_year_activation_course: 2010/2011
                      website_university: http://www.nomeconservatorio.it
                      website_course: http://....
                      curriculum_list:
                        - curriculum_name: NON DIFFERENZIATO
                        - curriculum_description: relativamente agli insegnamenti a scelta si invita a consultare il riferimento del corso sul portale istituzionale
                          curriculum_learnings: 
                          - degree_course_year: 1
                            learnings:
                            - learning_ssd: null
                              learning_sad: COTP/06
                              learning_name: Ear training I
                              learning_code: '081360'
                              learning_cfu: null
                              learning_cfa: 10
                              learning_hour: 48
                              learning_language: IT
                              learning_ref: http://....
                            - learning_ssd: null
                              learning_sad: COTP/01
                              learning_name: Teorie e tecniche dell'armonia I
                              learning_code: '0489'
                              learning_cfu: null
                              learning_cfa: 7
                              learning_hour: 36
                              learning_language: IT
                              learning_ref: http://....  
                Università:
                  value:
                      programme_type_code: LT
                      programme_access: free
                      course_location: '015146'
                      remote_mode: on-site
                      course_area: Ingegneria industriale
                      degree_course_language: IT
                      degree_course_period_years: 3
                      degree_course_code: '353'
                      total_credits: 180
                      academic_year: 2023/2024
                      first_year_activation_course: 2010/2011
                      website_university: http://www.ingindinf.polimi.it
                      website_course: http://....
                      curriculum_list:
                        - curriculum_name: NON DIFFERENZIATO
                          curriculum_description: relativamente agli insegnamenti a scelta si invita a consultare il riferimento del corso sul portale istituzionale
                          curriculum_learnings: 
                          - degree_course_year: 1
                            learnings:
                            - learning_ssd: MAT/03
                              learning_sad: null
                              learning_name: ANALISI E GEOMETRIA 1
                              learning_code: '081360'
                              learning_cfu: 10
                              learning_cfa: null
                              learning_hour: 48
                              learning_language: IT
                              learning_ref: http://....
                            - learning_ssd: CHIM/07
                              learning_sad: null
                              learning_name: FONDAMENTI DI CHIMICA
                              learning_code: '081374'
                              learning_cfu: 7
                              learning_cfa: null
                              learning_hour: 36
                              learning_language: IT
                              learning_ref: http://....      
        '400':
          description: <b>Bad Request</b> - il server non può elaborare la richiesta del client a causa di una sintassi errata o di una richiesta non valida. <br> Esempi di cause
            <br> - Richiesta non valida
            <br> - Sintassi errata
            <br> - Parametro mancante
            <br> - Richiesta incompleta
            <br> - ...
        '500':
          description: Internal server error / Errore interno del server 
      
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/course_detail_request'
            examples:
              Esempio:
                value:
                  degree_course_code: '465'    
          application/xml:
            schema:
              type: object
              additionalProperties: false
              properties: {}
        description: ''
      
      operationId: educational-offering-detail
      description: <ul> <li>Requires the detail of a course. </li><li>Richiede il dettaglio di un corso.</li></ul>
      parameters: []
  /status:
    get:
      summary: Verifica dello stato delle API (Health Check)
      security: [{}]
      operationId: check-status
      description: Check the system's health status / Verificare lo stato di salute del sistema 
      tags:
        - health-check
      responses:
        '400':
          description: Bad Request
        '204':
          description: The service is running correctly / Il servizio è in esecuzione correttamente
        '500':
          description:  The service is not running. / Il servizio non è in esecuzione. 
components:
  headers:
    Retry-After:
      description: |-
        Retry contacting the endpoint *at least* after seconds.
        See https://tools.ietf.org/html/rfc7231#section-7.1.3
      schema:
        format: int32
        maximum: 186400
        minimum: 0
        type: integer
    X-RateLimit-Limit:
      description: The number of allowed requests in the current period / Numero di richieste consentite nel periodo attuale
      schema:
        format: int32
        maximum: 1000000
        minimum: 0
        type: integer
    X-RateLimit-Remaining:
      description: The number of remaining requests in the current period / Numero di richieste rimanenti nel periodo attuale 
      schema:
        format: int32
        maximum: 1000000
        minimum: 0
        type: integer
    X-RateLimit-Reset:
      description: The number of seconds left in the current period / Numero di secondi rimanenti nel periodo attuale
      schema:
        format: int32
        maximum: 186400
        minimum: 0
        type: integer
  schemas:
    course_list:
      nullable: true
      type: object
      additionalProperties: false
      description: List of active courses offered by the Institute in an academic year. / Lista dei corsi attivi offerti dall'Istituto in un anno accademico.
      properties:
        degree_courses:
          type: array
          maxItems: 256
          minItems: 0
          description: List of active courses offered by the Institute in an academic year. / Lista dei corsi attivi offerti dall'Istituto in un anno accademico.
          items:
            $ref: '#/components/schemas/degree_courses'
        meta:
            $ref: '#/components/schemas/meta'
    degree_courses:
      type: object
      additionalProperties: false
      description: Detailed course information / Informazioni dettagliate sul corso
      properties:
        programme_type_code:
          type: string
          description: Code of study program / codice del corso di studio
          example: 'LT'          
          minLength: 1
          maxLength: 256
        programme_access:
          type: string
          description: Access to the course / Accesso al corso
          example: free          
          minLength: 1
          maxLength: 99
          enum:
            - free
            - limited
        course_location:
          type: string
          description: Course location / Sede del corso
          example: Milano Bovisa
          minLength: 1
          maxLength: 99
        course_area:
          type: string
          description: Course area / Area del corso
          example: Ingegneria industriale          
          minLength: 1
          maxLength: 99
        degree_course_language:
          type: string
          description: Language of the degree class / Lingua della classe di laurea
          example: IT          
          minLength: 1
          maxLength: 20
        degree_course_period_years:
          type: integer
          format: int32
          description: Degree course duration in years / Durata corso di laurea in anni
          example: 3          
          minimum: 1
          maximum: 99
        degree_course_code:
          type: string
          description: Course code / Codice del corso          
          minLength: 1
          maxLength: 20
        total_credits:
          type: integer
          format: int32
          description: Total credits degree course / Totale crediti corso di laurea
          example: 180          
          minimum: 1
          maximum: 999
        academic_year:
          type: string
          description: Academic year / Anno accademico          
          minLength: 9
          maxLength: 9
          pattern: '^\d{4}/\d{4}$'
    meta:
      nullable: true
      type: object
      additionalProperties: false
      description: Informazioni del cursore
      properties:
        cursor:
          type: string
          description: Cursor / Cursore
          example: 'fowfio543s'
          nullable: true          
          minLength: 1
          maxLength: 512
    course_details:
      additionalProperties: false
      type: object
      description: Course detail / Dettagli corso
      properties:
        programme_type_code:
          type: string
          description: Code of study program / codice del corso di studio
          example: LT
          minLength: 1
          maxLength: 256
        programme_access:
          type: string
          description: Access to the course / Accesso al corso
          example: free          
          minLength: 1
          maxLength: 99
          enum:
            - free
            - limited
        course_location:
          type: string
          description: Course location / Sede del corso
          example: Milano Bovisa          
          minLength: 1
          maxLength: 99
        remote_mode:
          type: string
          description: Remote instruction method / Metodo istruzione remota
          example: on-site          
          minLength: 1
          maxLength: 99
          enum:
            - full-remote
            - on-site
            - hybrid
            - not-available
            - other  
        course_area:
          type: string
          description: Course area / Area del corso
          example: Ingegneria industriale          
          minLength: 1
          maxLength: 99
        degree_course_language:
          type: string
          description: Language of the degree class / Lingua della classe di laurea
          example: IT          
          minLength: 1
          maxLength: 20
        degree_course_period_years:
          type: integer
          format: int32
          description: Degree course duration in years / Durata corso di laurea in anni
          example: 3          
          minimum: 1
          maximum: 99
        degree_course_code:
          type: string
          description: Course code / Codice del corso          
          minLength: 1
          maxLength: 20
        total_credits:
          type: integer
          format: int32
          description: Total credits degree course / Totale crediti corso di laurea
          example: 180          
          minimum: 1
          maximum: 999
        academic_year:
          type: string
          description: Academic year / Anno accademico          
          minLength: 9
          maxLength: 9
          pattern: '^\d{4}/\d{4}$'
        first_year_activation_course:
          type: string
          description: First year of course activation / Primo anno di attivazione del corso          
          minLength: 1
          maxLength: 20
        website_university:
          type: string
          description: University website / Sito università          
          minLength: 1
          maxLength: 999
        website_course:
          type: string
          description: Course website / Sito corso di studi          
          minLength: 1
          maxLength: 999
        curriculum_list:
          type: array
          minItems: 0
          description: Course list / Elenco corsi
          items:
            $ref: '#/components/schemas/curriculum_list'
    curriculum_list:
      nullable: true
      type: object
      additionalProperties: false     
      description: Course list / Elenco corsi
      properties:
        curriculum_name:
          type: string
          description: Address, course, specialisation strand / Indirizzo, percorso, specializzazione filone formativo
          example: NON DIFFERENZIATO          
          minLength: 1
          maxLength: 100
        curriculum_description:
          type: string
          description: Curriculum details about the learnings and how to interpretate the follow learnings list / Descrizione della lista degli insegnamenti e come interpretarla in ottica di manifesto         
          example: 'relativamente agli insegnamenti a scelta si invita a consultare il riferimento del corso sul portale istituzionale'
          minLength: 1
          maxLength: 4096
        curriculum_learnings:
          type: array
          minItems: 0
          description: Teaching list / Elenco insegnamenti
          items:
            $ref: '#/components/schemas/curriculum_learnings'
    curriculum_learnings:
      type: object
      additionalProperties: false
      description: Teaching list / Elenco insegnamenti
      properties:
        degree_course_year:
          type: integer
          format: int32
          description: Course teaching year / Anno insegnamento corso
          example: 1          
          minimum: 1
          maximum: 99
        learnings:
          type: array
          minItems: 0
          description: Teaching list / Lista insegnamenti
          items:
            $ref: '#/components/schemas/learnings'
    learnings:
      type: object
      additionalProperties: false
      description: Teaching list / Lista insegnamenti
      properties:
        learning_ssd:
          type: string
          description: Learning reference / Riferimento insegnamento
          example: MAT/03
          minLength: 1
          maxLength: 256
          nullable: true
        learning_sad:
          type: string
          description: Learning reference / Riferimento insegnamento
          example: 
          minLength: 1
          maxLength: 256
          nullable: true
        learning_name:
          type: string
          description: Learning name / Nome insegnamento
          example: ANALISI E GEOMETRIA 1          
          minLength: 1
          maxLength: 256
        learning_code:
          type: string
          description: Learning Code / Codice insegnamento
          example: '081360'          
          minLength: 1
          maxLength: 256
        learning_cfu:
          type: integer
          format: int32
          description: Learning CFU / CFU insegnamento
          example: 10          
          minimum: 1
          maximum: 999
          nullable: true
        learning_cfa:
          type: integer
          format: int32
          description: Learning CFA / CFA insegnamento
          example: 10          
          minimum: 1
          maximum: 999
          nullable: true  
        learning_hour:
          type: integer
          format: int32
          description: Learning hours / Ore insegnamento
          example: 48          
          minimum: 0
          maximum: 999
        learning_language:
          type: string
          description: Learning language / Lingua insegnamento
          example: IT          
          minLength: 1
          maxLength: 256
        learning_ref:
          type: string
          description: Learning site / Sito insegnamento
          example: http://....          
          minLength: 1
          maxLength: 256
    course_list_request:
      type: object
      additionalProperties: false
      description: Request the list of active courses offered by the Institute in an academic year. / Richiedi la lista dei corsi attivi offerti dall'Istituto in un anno accademico.
      properties:
        academic_year:
          type: string
          description: Academic year / Anno accademico
          example: 2023/2024         
          minLength: 9
          maxLength: 9
          pattern: '^\d{4}/\d{4}$'
        cursor:
          type: string
          description: Cursor / Cursore
          example: 'fowfio543s'
          nullable: true
          minLength: 1
          maxLength: 512
      required:
        - academic_year
    course_detail_request:
      type: object
      additionalProperties: false
      description: Request enrollment of a student's enrollment / Richiesta iscrizione di una studentessa o uno studente
      properties:
        degree_course_code:
          type: string
          description: Course code / Codice del corso
          minLength: 1
          maxLength: 20
  requestBodies: {}
  responses: {}
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: PASETO 
servers:
  - url: 'https://localhost:8080/api'
    description: localhost
tags:
  - name: IFS01.1 - educational-offering-list
  - name: IFS01.2 - educational-offering-detail
  - name: health-check