openapi: 3.0.0
info:
  title: IFS05 - Qualification Change request/ Rettifica titoli
  x-summary: Requests the rectification of missing or excess entry data for a student who is attending or has attended. / Richiede la rettifica dei dati di un’iscrizione mancante o in eccesso per una studentessa o uno studente che stia frequentando o abbia frequentato.
  version: 1.0.0
  description: |
        Requests the rectification of missing or excess entry data for a student who is attending or has attended. / Richiede la rettifica dei dati di un’iscrizione mancante o in eccesso per una studentessa o uno studente che stia frequentando o abbia frequentato.
  contact:
    name: helpdesk
    email: helpdesk@gmail.com
  x-api-id: 00000000-0000-0000-0000-000000000000
  termsOfService: 'http://swagger.io/terms/'
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
security: [{}]
paths:
  '/academic-qualification-change-request':
    post:
      summary: Academic qualification change request / Richiesta di rettifica dei titoli conseguti
      operationId: academic-qualification-change-request
      tags:
        - academic-qualification-change-request
      security:
        - bearerAuth: []
      parameters: []
      responses:
        '200':
          description: Academic qualification change request sent successfully / Richiesta di rettifica del titolo conseguito inviata con successo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/qualification_change_request_detail'
              examples:
                Example res 1:
                  value:
                    file_status: acquired
                    file_code: 6d183bc572f6b200015a4167
                    message: Richiesta di rettifica del titolo conseguito acquisita con successo
        '404':
          description: Student not found / Studente non trovato
        '500':
          description: Internal server error / Errore interno del server 
      description: Create an academic qualification change request / Crea una richiesta di rettifica del titolo conseguito
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/qualification_change_request'
            examples:
              Example post 1:
                value:
                  tax_code: RSSMRA80A01F205D
                  person_id: 12345678A
                  reason: Modifica iscrizione xxx
                  attributes:
                      - attribute_name: institute_Name
                        current: Università degli studi di Milano
                        suggested: Università degli studi di Roma 'La Sapienza'
                      - attribute_name: course_type
                        current: Laurea
                        suggested: Corso di Laurea
                      - attribute_name: qualification_year
                        current: 2021/2022
                        suggested: 2022/2023
                      - attribute_name: course_year
                        current: 2° anno
                        suggested: 3° anno
                  request: Testo con la richiesta di rettifica
                  note: Note aperte studentessa o studente
          application/xml:
            schema:
              type: object
              additionalProperties: false
              properties: {}
        description: 'Request di esempio'
    parameters: []
  '/academic-qualification-change-request-status':

    post:
      summary: Status of academic qualification change request / Stato della richiesta di rettifica di un titolo conseguito
      tags:
        - academic-qualification-change-request-status
      parameters: []
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Request executed successfully / Richiesta eseguita con successo (annulamento)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/qualifications_change_request'
              examples:
                Example 1:
                  value: 
                    qualification_change_request:
                      - file_status: approved
                        file_code: 6d183bc572f6b200015a4167
                        message: testo messaggio
                      - file_status: rejected
                        file_code: 6d183b54654127dfhh15a4167
                        message: testo messaggio  
        '404':
          description: Registration correction not found / Rettifica iscrizione non trovata
        '500':
          description: Internal server error / Errore interno del server 
      operationId: status-academic-qualification-change-request
      description: Retrieve the status of the academic qualification change request satus / Permette di recuperare lo stato di una richiesta di rettifica del titolo conseguito
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/academic_qualification_change_request'
            examples:
              Example post 1:
                value:
                  tax_code: LNGDVD80L31B354S
                  person_id: 12345678A
                  file_code: 6d183bc572f6b200015a4167
          application/xml:
            schema:
              type: object
              additionalProperties: false
              properties: {}
        description: 'Request di esempio'
  '/academic-qualification-change-request-cancellation':
    post:
      summary: academic qualification change request cancellation / Richiesta di annullamento della richiesta di rettific di un titolo conseguito
      tags:
        - academic-qualification-change-request-cancellation

      security:
        - bearerAuth: []
      responses:
        '200':
          description: Cancellation of academic qualification change request completed successfully / Aannullamento della richiesta di rettifica del titolo eseguita con successo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/qualification_change_request_detail'
              examples:
                Example 1:
                  value:
                    file_status: approved
                    file_code: 6d183bc572f6b200015a4167
                    message: messaggio di testo
        '500':
          description: Internal server error / Errore interno del server 
      description: cancellation change request / Effettua la richiesta di annullamento rettifica 
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/academic_qualification_change_request'
            examples:
              Example post 1:
                value:
                  tax_code: LNGDVD80L31B354S
                  person_id: 12345678A
                  file_code: 6d183bc572f6b200015a4167
          application/xml:
            schema:
              type: object
              additionalProperties: false
              properties: {}
        description: 'Request di esempio'   
      operationId: academic-qualification-change-request-cancellation 
    parameters: []
  '/academic-qualifications-issues':
    post:
      summary: Open the issues on academic qualifications data  / Apre le anomalie sui dati dei titoli accademici
      tags:
        - academic-qualifications-issues
      security:
        - bearerAuth: []
      parameters: []
      responses:
        '200':
          description: issues created successfully / Anomalie create con successo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/issue_detail'
              examples:
                Example res 1:
                  value:
                    file_status: approved
                    file_code: 6d183bc572f6b200015a4167
                    message: Testo messaggio
        '404':
          description: Student not found / Studente non trovato
        '500':
          description: Internal server error / Errore interno del server 
      description: Report issues on academic qualifcations data  / Permette di segnalare le anomalie sui dati dei titoli accademici
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/issue_request'
            examples:
              Example post 1:
                value:
                  subscriber_id: "1234"
                  subscriber_name: ANIS
                  subscriber_message: It wasn't possible to load all the academic qualifcations of this student
                  data_request_timestamp: 2019-10-12T07:20:50.52Z
                  personal_data:
                    tax_code: RSSMRA80A01F205D
                    person_id: AB123456C
                    given_name: null
                    family_name: null
                    birth_date: null
                    birth_place: null
                    issues:
                      - attribute_name: degree_course_code
                        issue_description: degree course code didn't find
                      - attribute_name: tax_code
                        issue_description: tax code didn't find on ANPR Master Data
                      - attribute_name: degree_course_year
                        issue_description: degree course can be only a numeric value
                  qualifications:
                    institute_code: '26'
                    institute_name: Università degli Studi di Roma 'La Sapienza'
                    qualification_name: Dottore magistrale
                    programme_type_code: MS
                    degree_course_code: '1573960'
                    degree_class_code: MSLM32
                    academic_qualification_date: '2022-07-01'
                    qualification_grade_value: '110'
                    qualification_grading_scale: '110'
                    qualification_grading_scale_minimum_grade: '66'
                    qualification_grading_scale_maximum_grade: '110'
                    issues:
                      - attribute_name: degree_course_code
                        issue_description: degree course code didn't find on the controlled vocabulary
                      - attribute_name: tax_code
                        issue_description: tax code didn't find on ANPR Master Data
                      - attribute_name: degree_course_year
                        issue_description: degree course can be only a numeric value
          application/xml:
            schema:
              type: object
              additionalProperties: false
              properties: {}
        description: ''
      operationId: academic-qualifcations-issues 
    parameters: []
  /status:
    get:
      summary: Verifica stato delle API (Health Check)
      operationId: check-status
      description: Verificare lo stato di salute del sistema
      tags:
        - health-check
      security: [{}]
      responses:
        '204':
          description: il servizio è in esecuzione correttamente.
        '500':
          description: il servizio non è in esecuzione.
components:
  headers:
    Retry-After:
      description: |-
        Retry contacting the endpoint *at least* after seconds.
        See https://tools.ietf.org/html/rfc7231#section-7.1.3
      schema:
        format: int32
        maximum: 186400
        minimum: 0
        type: integer
    X-RateLimit-Limit:
      description: The number of allowed requests in the current period
      schema:
        format: int32
        maximum: 1000000
        minimum: 0
        type: integer
    X-RateLimit-Remaining:
      description: The number of remaining requests in the current period
      schema:
        format: int32
        maximum: 1000000
        minimum: 0
        type: integer
    X-RateLimit-Reset:
      description: The number of seconds left in the current period
      schema:
        format: int32
        maximum: 186400
        minimum: 0
        type: integer
  schemas:
    qualification_change_request:
      type: object
      additionalProperties: false      
      description: qualification change request of a student's qualification / Richiesta creazione rettifica titolo di una studentessa o uno studente
      properties:
        tax_code:
          type: string
          description: Tax Identification Number / Codice fiscale
          pattern: '^[A-Z]{6}\d{2}[A-Z]\d{2}[A-Z]\d{3}[A-Z]$'
          example: RSSMRA80A01F205D
          minLength: 16
          maxLength: 16
        person_id:
          type: string
          description: ANPR Identifier / Identificativo ANPR 
          maxLength: 9
          minLength: 9
          pattern: "^[A-Z0-9]{9}$"
          example: AB123456C
          nullable: true
        reason:
          type: string
          description: Modification description / Descrizione modifica
          example: Modifica iscrizione xxx
          minLength: 1
          maxLength: 256
        attributes:
          $ref: '#/components/schemas/attributes'
        request:
          type: string
          description: qualification  chacge request Text / Testo con la richiesta di rettifica
          minLength: 1
          maxLength: 5000
        note:
          type: string
          description: Open notes from student / Note aperte studentessa o studente
          minLength: 1
          maxLength: 5000
      required:
        - tax_code
    qualifications_change_request:
      type: object
      additionalProperties: false
      description: Qualification change request information status / Stati richiesta modifica titoli della studentessa o dello studente
      properties:
        qualification_change_request:
          type: array
          minItems: 0
          maxItems: 256
          description: List of qualifications change request for student / Elenco variazioni titoli di una studentessa o di uno studente
          items:
            $ref: '#/components/schemas/qualification_change_request_detail'
    qualification_change_request_detail:
      additionalProperties: false
      type: object
      description: Status of an qualification change request for a student / Stato di una rettifica titolo per una studentessa o uno studente
      properties:
        file_status:
          type: string
          description: Status of an academic qualification change request for a student / Stato di una rettifica Titolo per una studentessa o uno studente
          minLength: 1
          maxLength: 256   
        file_code:
          type: string
          description: change request qualification code/ Codice Rettifica titolo
          minLength: 1
          maxLength: 256    
        message:
          type: string
          description: Change request message output / Messaggio esito richiesta rettifica
          minLength: 1
          maxLength: 256 
      required:
        - file_status
        - file_code
        - message
    attributes:
          additionalProperties: false
          type: array
          maxItems: 256
          minItems: 0
          description: List of attributes to be varied / Lista di attributi da variare
          items:
            $ref: '#/components/schemas/attribute'
    attribute:
      additionalProperties: false
      type: object
      description: attribute to modify / attributo da variare
      properties:
        attribute_name:
          type: string
          description: Attribute name to be changed  / Nome attributo da variare in fase di rettifica titolo
          minLength: 1
          maxLength: 256   
        current:
          type: string
          description: Current value to be rectified / Valore corrente da rettificare
          minLength: 1
          maxLength: 256    
        suggested:
          type: string
          description: New value to be rectified / Nuovo valore da rettificare
          minLength: 1
          maxLength: 256 
      required:
        - attribute_name
        - current
        - suggested
    academic_qualification_change_request:
      type: object
      additionalProperties: false      
      description: Request qualification of a student's qualification / Richiesta Titolo di una studentessa o uno studente
      properties:
        tax_code:
          type: string
          description: Tax Identification Number / Codice fiscale
          pattern: '^[A-Z]{6}\d{2}[A-Z]\d{2}[A-Z]\d{3}[A-Z]$'
          example: RSSMRA80A01F205D
          minLength: 16
          maxLength: 16
        person_id:
          type: string
          description: ANPR Identifier / Identificativo ANPR 
          maxLength: 9
          minLength: 9
          pattern: "^[A-Z0-9]{9}$"
          example: AB123456C
          nullable: true
        file_code:
          type: string
          description: qualification change request code/ Codice Rettifica titolo
          example: 6d183bc572f6b200015a4167
          minLength: 1
          maxLength: 64
      required:
        - tax_code     
        - file_code    
    issue_request:
      type: object
      additionalProperties: false      
      description: Academic change request / Richiesta di rettifica di una studentessa o uno studente
      properties:
        subscriber_id:
          type: string
          description: Applicant Identification Code / Codice identificativo richiedente
          example: '213521'
          minLength: 1
          maxLength: 2048
          
        subscriber_name:
          type: string
          description: Applicant name / Nome richiedente
          example: ANIS
          minLength: 1
          maxLength: 2048
          
        subscriber_message:
          type: string
          description: Applicant message / Messaggio richiedente
          example: It wasn't possible to load all the academic qualifications of this student
          minLength: 1
          maxLength: 2048
          
        data_request_timestamp:
          type: string
          format: date-time
          description: Timestamp request / Timestamp richiesta
          example: 2019-10-12T07:20:50.52Z
          minLength: 1
          maxLength: 36
          
        personal_data:
          $ref: '#/components/schemas/personal_data'
        qualifications:
          $ref: '#/components/schemas/qualifications'
    personal_data:
      type: object
      nullable: true
      additionalProperties: false
      description: Personal data of the student / Dati personali della studentessa o dello studente
      properties:
        tax_code:
          type: string
          description: Tax Identification Number / Codice Fiscale
          example: RSSMRA80A01F205D
          pattern: '^[A-Z]{6}\d{2}[A-Z]\d{2}[A-Z]\d{3}[A-Z]$'
          minLength: 16
          maxLength: 16
          nullable: true
        person_id:
          type: string
          description: ANPR Identifier / Identificativo ANPR 
          maxLength: 9
          minLength: 9
          pattern: "^[A-Z0-9]{9}$"
          example: AB123456C
          nullable: true
        given_name:
          type: string
          description: Name / Nome
          example: Mario
          pattern: ^[p{L}} ,.'-\s''-Ӑ]+$
          minLength: 1
          maxLength: 2048
          nullable: true
        family_name:
          type: string
          description: Surname / Cognome
          example: Rossi
          pattern: ^[p{L}} ,.'-\s''-Ӑ]+$
          minLength: 1
          maxLength: 2048
          nullable: true
        birth_date:
          type: string
          format: date
          example: 1990-05-17
          pattern: '^\d{4}-\d{2}-\d{2}$'
          description: Date of birth / Data di nascita
          nullable: true
        birth_place:
          type: string
          example: Rome
          description: Place of birth / Luogo di nascita
          minLength: 1
          maxLength: 2048
          nullable: true
        issues:
          additionalProperties: false
          type: array
          maxItems: 256
          minItems: 0
          description: List of issues to be varied / Lista di attributi da variare
          items:
            $ref: '#/components/schemas/issue'
    qualifications:
      type: object
      additionalProperties: false
      description: Degree detail / Dettaglio titolo
      properties:
        institute_code:
          type: string
          description: Institute identification code / Codice identificativo dell'istituto
          minLength: 2
          maxLength: 2
        institute_name:
          type: string
          description: Name of institution / Nome dell'istituto
          minLength: 1
          maxLength: 2048
        qualification_name:
          type: string
          description: Title of the degree / Denominazione del titolo di studio
          minLength: 1
          maxLength: 2048
        programme_type_code:
          type: string
          description: Code of study program / codice del corso di studio
          example: 'LM'
          minLength: 1
          maxLength: 2
        degree_course_code:
          type: string
          description: Course Code / Codice del corso
          minLength: 1
          maxLength: 20
        degree_class_code:
          type: string
          description: Identification code of the degree class / Codice identificativo della classe di laurea
          example: MSLM32
          minLength: 1
          maxLength: 20
        academic_qualification_date:
          type: string
          description: Date of graduation / Data di conseguimento del titolo di studio
          pattern: '^[0-9]{4}-[0-9]{2}-[0-9]{2}$'
          example: '2023-05-15'
          format: date
        qualification_grade_value:
          type: string
          description: Grade obtained upon graduation / Voto ottenuto al conseguimento del titolo di studio
          minLength: 1
          maxLength: 32
          example: '110'
        qualification_grading_scale:
          type: string
          minLength: 1
          maxLength: 32
          example: '110'
          description: Rating scale / Scala di valutazione
        qualification_grading_scale_minimum_grade:
          type: string
          format: int32
          minLength: 1
          maxLength: 32
          example: '66'
          description: Minimum course grade / Voto minimo del corso
        qualification_grading_scale_maximum_grade:
          type: string
          minLength: 1
          maxLength: 32
          example: '110'
          description: Highest course grade / Voto massimo del corso
        issues:
          additionalProperties: false
          type: array
          maxItems: 256
          minItems: 0
          description: List of issues to be varied / Lista di attributi da variare
          items:
            $ref: '#/components/schemas/issue'
    issue:
      additionalProperties: false
      type: object
      description: Status of an academic change request for a student / Stato di una rettifica per una studentessa o uno studente
      properties:
        attribute_name:
          type: string
          description: Attribute name to be changed  / Nome attributo da variare in fase di rettifica iscrizione
          
          minLength: 1
          maxLength: 256
        issue_description:
          type: string
          description: New value to be rectified / Nuovo valore da rettificare
          
          minLength: 1
          maxLength: 256 
      required:
        - attribute_name
        - issue_description
    issue_detail:
      additionalProperties: false
      type: object
      description: Status of an academic change request for a student / Stato di una rettifica per una studentessa o uno studente
      properties:
        file_status:
          type: string
          description: Status of an academic change request for a student / Stato di una rettifica per una studentessa o uno studente
          
          minLength: 1
          maxLength: 256
          enum:
            - approved
            - rejected
            - acquired
        file_code:
          type: string
          description: Change request code/ Codice rettifica 
          
          minLength: 1
          maxLength: 256    
        message:
          type: string
          description: Change request message output / Messaggio esito richiesta rettifica
          
          minLength: 1
          maxLength: 256 
      required:
        - file_status
        - file_code
        - message
  requestBodies: {}
  responses: {}
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: PASETO  
servers:
  - url: 'https://localhost:8080/api'
    description: localhost
tags:
  - name: academic-qualification-change-request
  - name: academic-qualification-change-request-status
  - name: academic-qualification-change-request-cancellation
  - name: academic-qualifications-issues
  - name: health-check