openapi: 3.0.0
x-stoplight:
  id: 0f56e32f16f60
info:
  title: IFS04 - Academic enrollment change request  / Rettifica iscrizioni accademiche
  x-summary: Requests the rectification of missing or excess entry data for a student who is attending or has attended. / Richiede la rettifica dei dati di un’iscrizione mancante o in eccesso per una studentessa o uno studente che stia frequentando o abbia frequentato.
  version: 1.0.0
  description: |
        Requests the rectification of missing or excess entry data for a student who is attending or has attended. / Richiede la rettifica dei dati di un’iscrizione mancante o in eccesso per una studentessa o uno studente che stia frequentando o abbia frequentato.
  contact:
    name: helpdesk
    email: helpdesk@gmail.com
  x-api-id: 00000000-0000-0000-0000-000000000000
  termsOfService: 'http://swagger.io/terms/'
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
security: [{}]
paths:
  '/academic-enrollment-change-request':
    post:
      summary: (OK) Correction of student registration / Rettifica iscrizione studente
      tags:
        - academic-enrollment-change-request
      security:
        - bearerAuth: []
      parameters: []
      responses:
        '200':
          description: Registration correction request sent successfully / Richiesta rettifica iscrizione inviata con successo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/change_request_detail'
              examples:
                Example res 1:
                  value:
                    file_status: acquired
                    file_code: 6d183bc572f6b200015a4167
                    message: Richiesta rettifica iscrizione acquisita
        '404':
          description: Student not found / Studente non trovato
        '500':
          description: Internal server error / Errore interno del server 
      description: Allows  to create a request to correct data relating to a student's registration / Permette di creare una richiesta di rettifica dei dati relativi alle iscrizioni di una studentessa o uno studente.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/change_request'
            examples:
              Example post 1:
                value:
                  tax_code: RSSMRA80A01F205D
                  person_id: 12345678A
                  reason: Modifica iscrizione xxx
                  attributes:
                      - attribute_name: institute_Name
                        current: Università degli studi di Milano
                        suggested: Università degli studi di Roma 'La Sapienza'
                      - attribute_name: course_type
                        current: Laurea
                        suggested: Corso di Laurea
                      - attribute_name: enrollment_year
                        current: 2021/2022
                        suggested: 2022/2023
                      - attribute_name: course_year
                        current: 2° anno
                        suggested: 3° anno
                  request: Testo con la richiesta di rettifica
                  note: Note aperte studentessa o studente
          application/xml:
            schema:
              type: object
              additionalProperties: false
              properties: {}
        description: ''
      operationId: academic-enrollment-change-request
    parameters: []
  '/academic-enrollment-change-request-status':
  
    post:
      summary: (OK) Student enrollment correction detail / Dettaglio rettifica iscrizione studentessa o studente
      tags:
        - academic-enrollment-change-request-status
      parameters: []
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Request executed successfully / Richiesta eseguita con successo (annulamento)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/enrollments_change_request'
              examples:
                Example 1:
                  value: 
                    enrollment_change_request:
                      - file_status: approved
                        file_code: 6d183bc572f6b200015a4167
                        message: testo messaggio
                      - file_status: rejected
                        file_code: 6d183b54654127dfhh15a4167
                        message: testo messaggio  
        '404':
          description: Registration correction not found / Rettifica iscrizione non trovata
        '500':
          description: Internal server error / Errore interno del server 
      description: Allows you to retrieve the status of a registration adjustment request via its identifier / Permette di recuperare lo stato di una richiesta di rettifica iscrizione tramite il suo identificativo
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/enrollment_change_request'
            examples:
              Example post 1:
                value:
                  tax_code: RSSMRA80A01F205D
                  person_id: 12345678A
                  file_code: 6d183bc572f6b200015a4167
          application/xml:
            schema:
              type: object
              additionalProperties: false
              properties: {}
        description: 'Esempio richiesta'
      operationId: academic-enrollment-change-request-statu
  '/academic-enrollment-change-request-cancellation':
    post:
      summary: Cancellation of change request / Richiesta di annullamento rettifica
      tags:
        - academic-enrollment-change-request-cancellation
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Request for cancellation of rectification completed successfully / Richiesta annullamento rettifica eseguita con successo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/change_request_detail'
              examples:
                Example 1:
                  value:
                    file_status: approved
                    file_code: 6d183bc572f6b200015a4167
                    message: messaggio di testo
        '500':
          description: Internal server error / Errore interno del server 
      operationId: rectification-cancellation
      description: Rectification cancellation request / Effettua la richiesta di annullamento rettifica 
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/enrollment_change_request'
            examples:
              Example post 1:
                value:
                  tax_code: RSSMRA80A01F205D
                  person_id: 12345678A
                  file_code: 6d183bc572f6b200015a4167
          application/xml:
            schema:
              type: object
              additionalProperties: false
              properties: {}
        description: 'Esempio richiesta'            
    parameters: []
  '/academic-issue-change-request':
    post:
      summary: Reporting any anomalies in academic enrollment data / Comunicazione di eventuali anomalie sui dati delle iscrizioni accademiche
      tags:
        - academic-issue-change-request
      security:
        - bearerAuth: []
      parameters: []
      responses:
        '200':
          description: Registration correction request sent successfully / Richiesta rettifica inviata con successo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/issue_detail'
              examples:
                Example res 1:
                  value:
                    file_status: approved
                    file_code: 6d183bc572f6b200015a4167
                    message: Testo messaggio
        '404':
          description: Student not found / Studente non trovato
        '500':
          description: Internal server error / Errore interno del server 
      description: Allows to report an anomaly in the enrollment data of a student. / Permette di segnalare una anomalia dei dati relativi alle iscrizioni di una studentessa o uno studente.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/issue_request'
            examples:
              Example post 1:
                value:
                  subscriber_id: "1234"
                  subscriber_name: ANIS
                  subscriber_message: It wasn't possible to load all the enrollments of this student
                  data_request_timestamp: 2019-10-12T07:20:50.52Z
                  personal_data:
                    tax_code: RSSMRA80A01F205D
                    person_id: AB123456C
                    given_name: null
                    family_name: null
                    birth_date: null
                    birth_place: null
                    issues:
                      - attribute_name: degree_course_code
                        issue_description: degree course code didn't find on the controlled vocabulary
                      - attribute_name: tax_code
                        issue_description: tax code didn't find on ANPR Master Data
                      - attribute_name: degree_course_year
                        issue_description: degree course can be only a numeric value
                  enrollments:
                    institute_code: '16'
                    institute_name: Milano - Politecnico
                    programme_type_code: MS
                    degree_course_code: '1573960'
                    degree_class_code: LM-32
                    academic_year: 2021/2022
                    degree_course_year: 3
                    status: attivo
                    issues:
                      - attribute_name: degree_course_code
                        issue_description: degree course code didn't find on the controlled vocabulary
                      - attribute_name: tax_code
                        issue_description: tax code didn't find on ANPR Master Data
                      - attribute_name: degree_course_year
                        issue_description: degree course can be only a numeric value
          application/xml:
            schema:
              type: object
              additionalProperties: false
              properties: {}
        description: ''
      operationId: academic-issue-change-request 
    parameters: []
  /status:
    get:
      summary: Verifica stato delle API (Health Check)
      operationId: check-status
      description: Verificare lo stato di salute del sistema
      tags:
        - health-check
      security: [{}]
      responses:
        '204':
          description: il servizio è in esecuzione correttamente.
        '500':
          description: il servizio non è in esecuzione.
components:
  headers:
    Retry-After:
      description: |-
        Retry contacting the endpoint *at least* after seconds.
        See https://tools.ietf.org/html/rfc7231#section-7.1.3
      schema:
        format: int32
        maximum: 186400
        minimum: 0
        type: integer
    X-RateLimit-Limit:
      description: The number of allowed requests in the current period
      schema:
        format: int32
        maximum: 1000000
        minimum: 0
        type: integer
    X-RateLimit-Remaining:
      description: The number of remaining requests in the current period
      schema:
        format: int32
        maximum: 1000000
        minimum: 0
        type: integer
    X-RateLimit-Reset:
      description: The number of seconds left in the current period
      schema:
        format: int32
        maximum: 186400
        minimum: 0
        type: integer
  schemas:
    change_request:
      type: object
      additionalProperties: false
      x-jsonld-type: https://w3id.org/italia/onto/CPV/Person
      x-jsonld-context:
        CPV: https://w3id.org/italia/onto/CPV/Person
        tax_code: CPV:taxCode
        person_id: CPV:personID
      x-examples:
        Example 1:
          tax_code: RSSMRA80A01F205D
          person_id: 12345678A
          reason: Modifica iscrizione xxx
          attributes:
              - attribute_name: institute_name
                current: Università degli studi di Milano
                suggested: Università degli studi di Roma 'La Sapienza'
              - attribute_name: degree_course_type
                current: Laurea
                suggested: Corso di Laurea
              - attribute_name: registratio_year
                current: 2021/2022
                suggested: 2022/2023
              - attribute_name: degree_cours_Year
                current: 2° anno
                suggested: 3° anno
          request: Testo con la richiesta di rettifica
          note: Note aperte dello studente/ex studente
      x-stoplight:
        id: b40e2be27c423
      description: academic enrollment change request / richiesta di rettifica di iscrizione di una studentessa o uno studente
      properties:
        tax_code:
          type: string
          description: Tax Identification Number / Codice fiscale
          pattern: '^[A-Z]{6}\d{2}[A-Z]\d{2}[A-Z]\d{3}[A-Z]$'
          example: RSSMRA80A01F205D
          minLength: 16
          maxLength: 16
          readOnly: true
        person_id:
          type: string
          description: ANPR Identifier / Identificativo ANPR 
          maxLength: 9
          minLength: 9
          example: AB123456C
          readOnly: true
        reason:
          type: string
          description: Modification description / Descrizione modifica
          example: Modifica iscrizione xxx
          minLength: 1
          maxLength: 256
          readOnly: true  
        attributes:
          $ref: '#/components/schemas/attributes'
        request:
          type: string
          description: Text with request for rectification / Testo con la richiesta di rettifica
          readOnly: true
          minLength: 1
          maxLength: 5000
        note:
          type: string
          description: Open notes from student / Note aperte studentessa o studente
          readOnly: true
          minLength: 1
          maxLength: 5000
      required:
        - tax_code
    issue_request:
      type: object
      additionalProperties: false      
      x-examples:
        Example 1:
          subscriber_id: "1234"
          subscriber_name: ANIS
          subscriber_message: It wasn't possible to load all the enrollments of this student
          data_request_timestamp: "2023-12-04 01:00:00"
          personal_data:
            tax_code: RSSMRA80A01F205D
            person_id: AB123456C
            given_name: null
            family_name: null
            birth_date: null
            birth_place: null
            issues:
              - attribute_name: degree_course_code
                issue_description: degree course code didn't find on the controlled vocabulary
              - attribute_name: tax_code
                issue_description: tax code didn't find on ANPR Master Data
              - attribute_name: degree_course_year
                issue_description: degree course can be only a numeric value
          enrollments:
            institute_code: '16'
            institute_name: Milano - Politecnico
            programme_type_code: MS
            degree_course_code: '1573960'
            degree_class_code: LM-32
            academic_year: 2021/2022
            degree_course_year: A
            status: attivo
            issues:
              - attribute_name: degree_course_code
                issue_description: degree course code didn't find on the controlled vocabulary
              - attribute_name: tax_code
                issue_description: tax code didn't find on ANPR Master Data
              - attribute_name: degree_course_year
                issue_description: degree course can be only a numeric value
      x-stoplight:
        id: b40e2be27c423
      description: Academic change request / Richiesta di rettifica di una studentessa o uno studente
      properties:
        subscriber_id:
          type: string
          description: Applicant Identification Code / Codice identificativo richiedente
          example: '213521'
          minLength: 1
          maxLength: 2048
          readOnly: true
        subscriber_name:
          type: string
          description: Applicant name / Nome richiedente
          example: ANIS
          minLength: 1
          maxLength: 2048
          readOnly: true
        subscriber_message:
          type: string
          description: Applicant message / Messaggio richiedente
          example: It wasn't possible to load all the enrollments of this student
          minLength: 1
          maxLength: 2048
          readOnly: true
        data_request_timestamp:
          type: string
          format: date-time
          description: Timestamp request / Timestamp richiesta
          example: 2019-10-12T07:20:50.52Z
          minLength: 1
          maxLength: 36
          readOnly: true
        personal_data:
          $ref: '#/components/schemas/personal_data'
        enrollments:
          $ref: '#/components/schemas/enrollments'
    personal_data:
      type: object
      nullable: true
      additionalProperties: false
      x-jsonld-type: https://w3id.org/italia/onto/CPV/Person
      x-jsonld-context:
        CPV: https://w3id.org/italia/onto/CPV/Person
        given_name: CPV:givenName
        tax_code: CPV:taxCode
        family_name: CPV:familyName
        birth_date: CPV:birth_date
        birth_place: CPV:hasBirthPlace
        person_id: CPV:personID
      x-examples:
        Example 1:
          tax_code: RSSMRA80A01F205D
          person_id: AB123456C
          given_name: Mario
          family_name: Rossi
          birth_date: 1990-05-17
          birth_place: Roma
          issues:
            - attribute_name: degree_course_code
              issue_description: degree course code didn't find on the controlled vocabulary
      description: Personal data of the student / Dati personali della studentessa o dello studente
      properties:
        tax_code:
          type: string
          description: Tax Identification Number / Codice Fiscale
          example: RSSMRA80A01F205D
          pattern: '^[A-Z]{6}\d{2}[A-Z]\d{2}[A-Z]\d{3}[A-Z]$'
          minLength: 16
          maxLength: 16
          readOnly: true
          nullable: true
        person_id:
          type: string
          description: ANPR Identifier / Identificativo ANPR 
          maxLength: 9
          minLength: 9
          pattern: "^[A-Z0-9]{9}$"
          example: AB123456C
          readOnly: true
          nullable: true
        given_name:
          type: string
          description: Name / Nome
          example: Mario
          pattern: ^[p{L}} ,.'-\s''-Ӑ]+$
          readOnly: true
          minLength: 1
          maxLength: 2048
          nullable: true
        family_name:
          type: string
          description: Surname / Cognome
          example: Rossi
          pattern: ^[p{L}} ,.'-\s''-Ӑ]+$
          readOnly: true
          minLength: 1
          maxLength: 2048
          nullable: true
        birth_date:
          type: string
          format: date
          example: 1990-05-17
          pattern: '^\d{4}-\d{2}-\d{2}$'
          description: Date of birth / Data di nascita
          readOnly: true
          nullable: true
        birth_place:
          type: string
          example: Rome
          description: Place of birth / Luogo di nascita
          readOnly: true
          minLength: 1
          maxLength: 2048
          nullable: true
        issues:
          additionalProperties: false
          type: array
          maxItems: 256
          minItems: 0
          description: List of issues to be varied / Lista di attributi da variare
          items:
            $ref: '#/components/schemas/issue'
    enrollments:
      type: object
      additionalProperties: false
      x-jsonld-type: https://w3id.org/italia/onto/Learning
      x-jsonld-context:
        LEA: https://w3id.org/italia/onto/Learning/
        institute_code: LEA:instituteCode
        institute_name: LEA:instituteName
        programme_type_code: LEA:ProgrammeType
        degree_course_code: LEA:DegreeCourse
        degree_class_code: LEA:DegreeClass
        academic_year: LEA:AcademicYear
      x-examples:
        Example 1:
          institute_code: '16'
          institute_name: Milano - Politecnico
          programme_type_code: MS
          degree_course_code: '1576480'
          degree_class_code: LM-32
          academic_year: 2021/2022
          degree_course_year: 3
          status: attivo
          issues:
            - attribute_name: degree_course_code
              issue_description: degree course code didn't find on the controlled vocabulary
      description: Detailed enrollment information / Informazioni dettagliate sull'iscrizione
      properties:
        institute_code:
          type: string
          description: Institutional identification code / Codice identificativo dell’istituto  [** DA DEFINIRE PATTERN CORRETTO **]
          example: '16'
          readOnly: true
          minLength: 2
          maxLength: 2
        institute_name:
          type: string
          description: Institution name / Denominazione dell’istituto
          example: 'Milano - Politecnico'
          readOnly: true
          minLength: 1
          maxLength: 2048
        programme_type_code:
          type: string
          description: Code of study program / Codice del corso di studio
          example: 'LM'
          readOnly: true
          minLength: 1
          maxLength: 2
        degree_course_code:
          type: string
          description: Course code / Codice del corso
          readOnly: true
          minLength: 1
          maxLength: 20
        degree_class_code:
          type: string
          description: Identification code of the degree class / Codice identificativo della classe di laurea
          example: L-8
          readOnly: true
          minLength: 1
          maxLength: 20
        academic_year:
          type: string
          description: Last academic year in which enrollment in the student's course is recorded / Ultimo anno accademico in cui risulta l'iscrizione al corso della studentessa o dello studente 
          example: 2022/2023
          pattern: '^\d{4}/\d{4}$'
          readOnly: true
          minLength: 9
          maxLength: 9
        degree_course_year:
          type: integer
          format: int32
          description: Last year in which enrollment in the student's course is recorded / Ultimo anno in cui risulta l'iscrizione al corso della studentessa o dello studente
          example: 3
          pattern: ^\d{2}$
          readOnly: true
          minimum: 1
          maximum: 99
        status:
          type: string
          description: Enrollment status / Stato dell'iscrizione
          example: attivo
          readOnly: true
          minLength: 1
          maxLength: 20
          enum:
            - attivo
            - non attivo
            - sospeso
        issues:
          additionalProperties: false
          type: array
          maxItems: 256
          minItems: 0
          description: List of issues to be varied / Lista di attributi da variare
          items:
            $ref: '#/components/schemas/issue'
    issue:
      additionalProperties: false
      type: object
      x-examples:
        Example 1:
          attribute_name: degree_course_code
          issue_description: degree course code didn't find on the controlled vocabulary
      description: Status of an academic change request for a student / Stato di una rettifica per una studentessa o uno studente
      properties:
        attribute_name:
          type: string
          description: Attribute name to be changed  / Nome attributo da variare in fase di rettifica iscrizione
          readOnly: true
          minLength: 1
          maxLength: 256
        issue_description:
          type: string
          description: New value to be rectified / Nuovo valore da rettificare
          readOnly: true
          minLength: 1
          maxLength: 256 
      required:
        - attribute_name
        - issue_description
    enrollments_change_request:
      type: object
      additionalProperties: false
      x-examples:
        Example 1:
          enrollment_change_request:
            - file_status: approved
              file_code: 6d183bc572f6b200015a4167
              message: testo messaggio
            - file_status: rejected
              file_code: 6d183b54654127dfhh15a4167
              message: testo messaggio  
      description: Personal data of the student / Dati personali della studentessa o dello studente
      properties:
        enrollment_change_request:
          type: array
          minItems: 0
          maxItems: 256
          description: List of academic enrollments for student / Elenco iscrizioni di una studentessa o di uno studente
          items:
            $ref: '#/components/schemas/change_request_detail'
    change_request_detail:
      additionalProperties: false
      type: object
      x-examples:
        Example 1:
          file_status: accepted
          file_code: 908d3e72b51a6f0034e2a11c
          message: accettata
      description: Status of an academic enrollment change request for a student / Stato di una rettifica iscrizione per una studentessa o uno studente
      properties:
        file_status:
          type: string
          description: Status of an academic enrollment change request for a student / Stato di una rettifica iscrizione per una studentessa o uno studente
          readOnly: true
          minLength: 1
          maxLength: 256
          enum:
            - approved 
            - rejected
            - acquired
        file_code:
          type: string
          description: enrollment change request code/ Codice Rettifica iscrizioni
          readOnly: true
          minLength: 1
          maxLength: 256    
        message:
          type: string
          description: Change request message output / Messaggio esito richiesta rettifica
          readOnly: true
          minLength: 1
          maxLength: 256 
      required:
        - file_status
        - file_code
        - message
    issue_detail:
      additionalProperties: false
      type: object
      x-examples:
        Example 1:
          file_status: approved
          file_code: 908d3e72b51a6f0034e2a11c
          message: Testo messaggio
      description: Status of an academic change request for a student / Stato di una rettifica per una studentessa o uno studente
      properties:
        file_status:
          type: string
          description: Status of an academic change request for a student / Stato di una rettifica per una studentessa o uno studente
          readOnly: true
          minLength: 1
          maxLength: 256
          enum:
            - approved
            - rejected
            - acquired
        file_code:
          type: string
          description: Change request code/ Codice rettifica 
          readOnly: true
          minLength: 1
          maxLength: 256    
        message:
          type: string
          description: Change request message output / Messaggio esito richiesta rettifica
          readOnly: true
          minLength: 1
          maxLength: 256 
      required:
        - file_status
        - file_code
        - message
    attributes:
          additionalProperties: false
          type: array
          maxItems: 256
          minItems: 0
          description: List of attributes to be varied / Lista di attributi da variare
          items:
            $ref: '#/components/schemas/attribute'
    attribute:
      additionalProperties: false
      type: object
      x-examples:
        Example 1:
          attribute_name: degree_course_year
          current: 5
          suggested: 4
      description: Status of an enrollment change request for a student / Stato di una rettifica iscrizione per una studentessa o uno studente
      properties:
        attribute_name:
          type: string
          description: Attribute name to be changed  / Nome attributo da variare in fase di rettifica iscrizione
          readOnly: true
          minLength: 1
          maxLength: 256   
        current:
          type: string
          description: Current value to be rectified / Valore corrente da rettificare
          readOnly: true
          minLength: 1
          maxLength: 256    
        suggested:
          type: string
          description: New value to be rectified / Nuovo valore da rettificare
          readOnly: true
          minLength: 1
          maxLength: 256 
      required:
        - attribute_name
        - current
        - suggested
    enrollment_change_request:
      type: object
      additionalProperties: false
      x-jsonld-type: https://w3id.org/italia/onto/CPV/Person
      x-jsonld-context:
        CPV: https://w3id.org/italia/onto/CPV/Person
        LEA: https://w3id.org/italia/onto/Learning/
        institute_code: LEA:instituteCode
        tax_code: CPV:taxCode
        person_id: CPV:personID
      x-examples:
        Example 1:
          tax_code: RSSMRA80A01F205D
          person_id: 12345678A
          institute_code: AA
      x-stoplight:
        id: b40e2be27c423
      description: Request of a student's enrollment / Richiesta iscrizione di una studentessa o uno studente
      properties:
        tax_code:
          type: string
          description: Tax Identification Number / Codice fiscale
          pattern: '^[A-Z]{6}\d{2}[A-Z]\d{2}[A-Z]\d{3}[A-Z]$'
          example: RSSMRA80A01F205D
          minLength: 16
          maxLength: 16
          readOnly: false
        person_id:
          type: string
          description: National unique identifier / Identificativo unico nazionale
          example: 12345678A
          minLength: 9
          maxLength: 9
          readOnly: false  
        file_code:
          type: string
          description: enrollment change request code/ Codice Rettifica iscrizioni
          example: 6d183bc572f6b200015a4167
          minLength: 1
          maxLength: 64
          readOnly: false  
      required:
        - tax_code     
        - file_code
  requestBodies: {}
  responses: {}
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: PASETO  
servers:
  - url: 'https://localhost:8080/api'
    description: localhost
tags:
  - name: academic-enrollment-change-request
  - name: academic-enrollment-change-request-status
  - name: academic-enrollment-change-request-cancellation
  - name: academic-issue-change-request
  - name: health-check
  