openapi: 3.0.0
info:
  title: IFS04 - Academic enrollments change request  / Rettifica iscrizioni accademiche
  x-summary: Data academic enrollments change request / Richiede la rettifica dei dati delle iscrizioni accademiche
  version: 1.0.0
  description: |
        Data academic enrollments change request / Richiede la rettifica dei dati delle iscrizioni accademiche
  contact:
    name: helpdesk
    email: helpdesk@gmail.com
  x-api-id: 00000000-0000-0000-0000-000000000000
  termsOfService: 'http://swagger.io/terms/'
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
security: [{}]
paths:
  '/academic-enrollment-change-request':
    post:
      summary: Enrollment change request / Rettifica iscrizione studente
      tags:
        - IFS04.1 - academic-enrollment-change-request
      security:
        - bearerAuth: []
      parameters: []
      responses:
        '200':
          description: Change request sent successfully / Richiesta rettifica iscrizione inviata con successo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/change_request_detail'
              examples:
                Example:
                  value:
                    response_code: approved
                    file_status: acquired
                    file_code: 6d183bc572f6b200015a4167
                    message: Richiesta rettifica iscrizione acquisita
        '400':
          description: <b>Bad Request</b> - il server non può elaborare la richiesta del client a causa di una sintassi errata o di una richiesta non valida. <br> Esempi di cause
            <br> - Richiesta non valida
            <br> - Sintassi errata
            <br> - Parametro mancante
            <br> - Richiesta incompleta
            <br> - ...
        '500':
          description: Internal server error / Errore interno del server 
      description: Create an enrollment change request / Crea una richiesta di rettifica dei dati relativi alle iscrizioni di una studentessa o uno studente.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/change_request'
            examples:
              Example:
                value:
                  tax_code: RSSMRA80A01F205D
                  person_id: 12345678A
                  degree_course_code: '1573960'
                  reason: Modifica iscrizione xxx
                  attributes:
                      - attribute_name: institute_Name
                        current: Università degli studi di Milano
                        suggested: Università degli studi di Roma 'La Sapienza'
                      - attribute_name: course_type
                        current: Laurea
                        suggested: Corso di Laurea
                      - attribute_name: enrollment_year
                        current: 2021/2022
                        suggested: 2022/2023
                      - attribute_name: course_year
                        current: 2° anno
                        suggested: 3° anno
                  request: Testo con la richiesta di rettifica
                  note: Note aperte studentessa o studente
          application/xml:
            schema:
              type: object
              additionalProperties: false
              properties: {}
        description: ''
      operationId: academic-enrollment-change-request
    parameters: []
  '/academic-enrollment-change-request-status':
  
    post:
      summary: | 
        Retrieve the status of the academic enrollment change request / 
        Ottiene lo stato della richiesta di rettifica di una iscrizioni accademica
      tags:
        - IFS04.2 - academic-enrollment-change-request-status
      parameters: []
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Request executed successfully / Richiesta eseguita con successo (annulamento)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/enrollments_change_request'
              examples:
                Example:
                  value: 
                    enrollment_change_request:
                      - file_status: approved
                        file_code: 6d183bc572f6b200015a4167
                        message: testo messaggio
                      - file_status: rejected
                        file_code: 6d183b54654127dfhh15a4167
                        message: testo messaggio  
        '400':
          description: <b>Bad Request</b> - il server non può elaborare la richiesta del client a causa di una sintassi errata o di una richiesta non valida. <br> Esempi di cause
            <br> - Richiesta non valida
            <br> - Sintassi errata
            <br> - Parametro mancante
            <br> - Richiesta incompleta
            <br> - ...
        '500':
          description: Internal server error / Errore interno del server 
      description: Retrieve the status of enrollmet change request / Recupera lo stato di una richiesta di rettifica iscrizione tramite il suo identificativo
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/enrollment_change_request'
            examples:
              Example:
                value:
                  tax_code: RSSMRA80A01F205D
                  person_id: 12345678A
          application/xml:
            schema:
              type: object
              additionalProperties: false
              properties: {}
        description: 'Esempio richiesta'
      operationId: academic-enrollment-change-request-status
  '/academic-enrollment-change-request-cancellation':
    post:
      summary: | 
        Delete the change request / Richiesta di annullamento rettifica
      tags:
        - IFS04.3 - academic-enrollment-change-request-cancellation
      security:
        - bearerAuth: []
      responses:
        '200':
          description: > 
            Delete the change request / Richiesta di annullamento rettifica 
            1) status Approved= Richiesta di rettifica Cancellata   
            2) status Rejected= Richiesta di rettifica non cancellata ed ancora attivata 
          
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/change_request_detail'
              examples:
                Example:
                  value:
                    response_code: approved
                    file_status: approved
                    file_code: 6d183bc572f6b200015a4167
                    message: messaggio di testo
        '400':
          description: <b>Bad Request</b> - il server non può elaborare la richiesta del client a causa di una sintassi errata o di una richiesta non valida. <br> Esempi di cause
            <br> - Richiesta non valida
            <br> - Sintassi errata
            <br> - Parametro mancante
            <br> - Richiesta incompleta
            <br> - ...
        '500':
          description: Internal server error / Errore interno del server 
      operationId: rectification-cancellation
      description: Cancellation enrollment change request / Effettua la richiesta di annullamento rettifica 
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/enrollment_change_request_cancellation'
            examples:
              Example:
                value:
                  tax_code: RSSMRA80A01F205D
                  person_id: 12345678A
                  file_code: 6d183bc572f6b200015a4167
          application/xml:
            schema:
              type: object
              additionalProperties: false
              properties: {}
        description: 'Esempio richiesta'            
    parameters: []
  '/enrollments-issues':
    post:
      summary: | 
        Open the issues on academic enrollments data  / Apre le anomalie sui dati delle iscrizioni
      tags:
        - IFS04.4 - enrollments-issues
      security:
        - bearerAuth: []
      parameters: []
      responses:
        '200':
          description: issues created successfully / anomalie aperte con successo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/issue_detail'
              examples:
                Example:
                  value:
                    file_status: approved
                    file_code: 6d183bc572f6b200015a4167
                    message: Testo messaggio
        '400':
          description: <b>Bad Request</b> - il server non può elaborare la richiesta del client a causa di una sintassi errata o di una richiesta non valida. <br> Esempi di cause
            <br> - Richiesta non valida
            <br> - Sintassi errata
            <br> - Parametro mancante
            <br> - Richiesta incompleta
            <br> - ...
        '500':
          description: Internal server error / Errore interno del server 
      description: Report issue on enrollments data  / Permette di segnalare le anomalie sui dati delle iscrizioni
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/issue_request'
            examples:
              Example:
                value:
                  subscriber_id: "1234"
                  subscriber_name: ANIS
                  subscriber_message: Warning on some academic enrollments
                  data_request : 2019-10-12
                  personal_data:
                    tax_code: RSSMRA80A01F205D
                    person_id: AB123456C
                    given_name: null
                    family_name: null
                    birth_date: null
                    birth_place: null
                    issues:
                      - attribute_name: tax_code
                        issue_description: tax code didn't find on ANPR Master Data
                      - attribute_name: birth_date
                        issue_description: the correct birth date format is 1990-05-17
                      - issue_description: description note
                  enrollments:
                    - institute_code: '16'
                      institute_name: Milano - Politecnico
                      programme_type_code: MS
                      degree_course_code: '1573960'
                      degree_class_code: MSLM32
                      academic_year: 2021/2022
                      degree_course_year: 3
                      status: active
                      issues:
                        - attribute_name: degree_course_code
                          issue_description: degree course code didn't find on the controlled vocabulary
                        - attribute_name: degree_course_year
                          issue_description: degree course can be only a numeric value
                        - issue_description: description note
          application/xml:
            schema:
              type: object
              additionalProperties: false
              properties: {}
        description: ''
      operationId: enrollments-issues
    parameters: []
  /status:
    get:
      summary: Verifica stato delle API (Health Check)
      operationId: check-status
      description: Verificare lo stato di salute del sistema
      tags:
        - health-check
      security: [{}]
      responses:
        '400':
          description: Bad Request
        '204':
          description: il servizio è in esecuzione correttamente.
        '500':
          description: il servizio non è in esecuzione.
components:
  headers:
    Retry-After:
      description: |-
        Retry contacting the endpoint *at least* after seconds.
        See https://tools.ietf.org/html/rfc7231#section-7.1.3
      schema:
        format: int32
        maximum: 186400
        minimum: 0
        type: integer
    X-RateLimit-Limit:
      description: The number of allowed requests in the current period
      schema:
        format: int32
        maximum: 1000000
        minimum: 0
        type: integer
    X-RateLimit-Remaining:
      description: The number of remaining requests in the current period
      schema:
        format: int32
        maximum: 1000000
        minimum: 0
        type: integer
    X-RateLimit-Reset:
      description: The number of seconds left in the current period
      schema:
        format: int32
        maximum: 186400
        minimum: 0
        type: integer
  schemas:
    change_request:
      type: object
      additionalProperties: false      
      description: academic enrollment change request / richiesta di rettifica di iscrizione di una studentessa o uno studente
      properties:
        tax_code:
          type: string
          description: Tax Identification Number / Codice fiscale
          pattern: '^(?:[A-Z][AEIOU][AEIOUX]|[B-DF-HJ-NP-TV-Z]{2}[A-Z]){2}(?:[\dLMNP-V]{2}(?:A-EHLMPR-T|[DHPS][37PT][0L]|[ACELMRT][37PT][01LM]|[AC-EHLMPR-T][26NS][9V])|(?:[02468LNQSU][048LQU]|[13579MPRTV][26NS])B[26NS][9V])(?:[A-MZ][1-9MNP-V][\dLMNP-V]{2}|[A-M]0L)[A-Z]$'
          example: RSSMRA80A01F205D
          minLength: 16
          maxLength: 16
        person_id:
          type: string
          description: Unique National Identifier (ANPR ID) / Identificativo unico nazionale (ID ANPR) 
          maxLength: 9
          minLength: 9
          pattern: "^[A-Z0-9]{9}$"
          example: AB123456C
          nullable: true
        degree_course_code:
          type: string
          description: Course code / Codice del corso          
          minLength: 1
          maxLength: 20  
        reason:
          type: string
          description: change request description / Descrizione della richiesta di rettifica
          example: Modifica iscrizione xxx
          minLength: 1
          maxLength: 256
        attributes:
          $ref: '#/components/schemas/attributes'
        request:
          type: string
          description: Change request description / Descrizione della richiesta di rettifica
          minLength: 1
          maxLength: 5000
        note:
          type: string
          description: Open notes from student / Note aperte studentessa o studente
          minLength: 1
          maxLength: 5000
      required:
        - tax_code
    issue_request:
      type: object
      additionalProperties: false      
      description: Issue on enrollments data / Anomalie sui dati delle iscrizioni
      properties:
        subscriber_id:
          type: string
          description: Applicant Identification Code / Codice identificativo richiedente
          example: '213521'
          minLength: 1
          maxLength: 2048
        subscriber_name:
          type: string
          description: Applicant name / Nome richiedente
          example: ANIS
          minLength: 1
          maxLength: 2048
        subscriber_message:
          type: string
          description: Applicant message / Messaggio richiedente
          example: Warning on some academic enrollments
          minLength: 1
          maxLength: 2048
        data_request :
          type: string
          format: date
          description: Date request / Data richiesta
          example: 2019-10-12
          minLength: 1
          maxLength: 36
        personal_data:
          $ref: '#/components/schemas/personal_data'
        enrollments:
          type: array
          minItems: 0
          description: List of enrollments for student / Elenco iscrizioni di una studentessa o di uno studente
          items:
            $ref: '#/components/schemas/enrollment'
    personal_data:
      type: object
      nullable: true
      additionalProperties: false
      description: Personal data of the student / Dati personali della studentessa o dello studente
      properties:
        tax_code:
          type: string
          description: Tax Identification Number / Codice Fiscale
          example: RSSMRA80A01F205D
          pattern: '^(?:[A-Z][AEIOU][AEIOUX]|[B-DF-HJ-NP-TV-Z]{2}[A-Z]){2}(?:[\dLMNP-V]{2}(?:A-EHLMPR-T|[DHPS][37PT][0L]|[ACELMRT][37PT][01LM]|[AC-EHLMPR-T][26NS][9V])|(?:[02468LNQSU][048LQU]|[13579MPRTV][26NS])B[26NS][9V])(?:[A-MZ][1-9MNP-V][\dLMNP-V]{2}|[A-M]0L)[A-Z]$'
          minLength: 16
          maxLength: 16
          nullable: true
        person_id:
          type: string
          description: Unique National Identifier (ANPR ID) / Identificativo unico nazionale (ID ANPR) 
          maxLength: 9
          minLength: 9
          pattern: "^[A-Z0-9]{9}$"
          example: AB123456C
          nullable: true
        given_name:
          type: string
          description: Name / Nome
          example: Mario
          pattern: ^[p{L}} ,.'\s''-Ӑ]+$
          minLength: 1
          maxLength: 2048
          nullable: true
        family_name:
          type: string
          description: Surname / Cognome
          example: Rossi
          pattern: ^[p{L}} ,.'\s''-Ӑ]+$
          minLength: 1
          maxLength: 2048
          nullable: true
        birth_date:
          type: string
          format: date
          example: 1990-05-17
          pattern: '^\d{4}-\d{2}-\d{2}$'
          description: Date of birth / Data di nascita
          nullable: true
        birth_place:
          type: string
          example: Italia,RM,Roma
          description: Place of birth / Luogo di nascita
          minLength: 1
          maxLength: 2048
          nullable: true
          pattern: .*,[a-zA-Z]*,[a-zA-Z]*
        issues:
          additionalProperties: false
          type: array
          maxItems: 256
          minItems: 0
          description: List of issues / Lista di anomalie 
          items:
            $ref: '#/components/schemas/issue'
    enrollment:
      type: object
      additionalProperties: false
      description: Detailed enrollment information / Informazioni dettagliate sull'iscrizione
      properties:
        institute_code:
          type: string
          description: Institute identification code / Codice identificativo dell’istituto  
          example: '16'
          minLength: 1
          maxLength: 256
          nullable: true
        institute_name:
          type: string
          description: Institute's name / Denominazione dell'istituto
          example: 'Milano - Politecnico'
          minLength: 1
          maxLength: 2048
        programme_type_code:
          type: string
          description: Code of study program / Codice del corso di studio
          example: 'LM'
          minLength: 1
          maxLength: 256
        degree_course_code:
          type: string
          description: Course code / Codice del corso
          minLength: 1
          maxLength: 20
        degree_class_code:
          type: string
          description: Identification code of the degree class / Codice identificativo della classe di laurea
          example: MSLM32
          minLength: 1
          maxLength: 20
        academic_year:
          type: string
          description: Last academic year in which enrollment in the student's course is recorded / Ultimo anno accademico in cui risulta l'iscrizione al corso della studentessa o dello studente 
          example: 2022/2023
          pattern: '^\d{4}/\d{4}$'
          minLength: 9
          maxLength: 9
        degree_course_year:
          type: integer
          format: int32
          description: Last year in which enrollment in the student's course is recorded / Ultimo anno in cui risulta l'iscrizione al corso della studentessa o dello studente
          example: 3
          pattern: ^\d{1,2}$
          minimum: 1
          maximum: 99
        status:
          type: string
          description: Enrollment status / Stato dell'iscrizione
          example: active
          minLength: 1
          maxLength: 20
          enum:
            - active
            - inactive
            - wait
        issues:
          additionalProperties: false
          type: array
          maxItems: 256
          minItems: 0
          description: List of issues / Lista di anomalie
          items:
            $ref: '#/components/schemas/issue'
    issue:
      additionalProperties: false
      type: object
      description: Status of an academic change request for a student / Stato di una rettifica per una studentessa o uno studente
      properties:
        attribute_name:
          type: string
          nullable: true
          description: Attribute name to be changed  / Nome attributo da variare in fase di rettifica iscrizione
          minLength: 1
          maxLength: 256
        issue_description:
          type: string
          description: New value to be rectified / Nuovo valore da rettificare
          minLength: 1
          maxLength: 256 
      required:
        - issue_description
    enrollments_change_request:
      type: object
      additionalProperties: false
      description: Personal data of the student / Dati personali della studentessa o dello studente
      properties:
        enrollment_change_request:
          type: array
          minItems: 0
          maxItems: 256
          description: List of tudent academic enrollments / Elenco iscrizioni accademiche
          items:
            $ref: '#/components/schemas/change_request_detail'
    change_request_detail:
      additionalProperties: false
      type: object
      description: Status of an academic enrollment change request for a student / Stato di una rettifica iscrizione per una studentessa o uno studente
      properties:
        response_code:
          type: string
          description: response code / codice della risposta
          minLength: 1
          maxLength: 256
          enum:
            - approved 
            - rejected
        file_status:
          type: string
          description: Status of an academic enrollment change request for a student / Stato di una rettifica iscrizione per una studentessa o uno studente
          minLength: 1
          maxLength: 256
          enum:
            - approved 
            - rejected
            - acquired
            - cancelled
        file_code:
          type: string
          description: enrollment change request code/ Codice Rettifica iscrizioni
          minLength: 1
          maxLength: 256    
        message:
          type: string
          description: Change request message output / Messaggio esito richiesta rettifica
          minLength: 1
          maxLength: 256 
      required:
        - response_code
        - file_status
        - file_code
        - message
    issue_detail:
      additionalProperties: false
      type: object
      description: Status of an academic change request for a student / Stato di una rettifica per una studentessa o uno studente
      properties:
        file_status:
          type: string
          description: Status of an academic change request for a student / Stato di una rettifica per una studentessa o uno studente          
          minLength: 1
          maxLength: 256
          enum:
            - approved
            - rejected
            - acquired
        file_code:
          type: string
          description: Change request code/ Codice rettifica          
          minLength: 1
          maxLength: 256    
        message:
          type: string
          description: Change request message output / Messaggio esito richiesta rettifica         
          minLength: 1
          maxLength: 256 
      required:
        - file_status
        - file_code
        - message
    attributes:
          additionalProperties: false
          type: array
          maxItems: 256
          minItems: 0
          description: List of attributes to be changed / Lista di attributi da variare
          items:
            $ref: '#/components/schemas/attribute'
    attribute:
      additionalProperties: false
      type: object
      description: Status of an enrollment change request for a student / Stato di una rettifica iscrizione per una studentessa o uno studente
      properties:
        attribute_name:
          type: string
          nullable: true
          description: Attribute name to be changed  / Nome attributo da variare in fase di rettifica iscrizione
          minLength: 1
          maxLength: 256   
        current:
          type: string
          description: Current value to be rectified / Valore corrente da rettificare
          minLength: 1
          maxLength: 256    
        suggested:
          type: string
          description: New value to be rectified / Nuovo valore da rettificare
          minLength: 1
          maxLength: 256 
      required:
        - attribute_name
        - current
        - suggested
    enrollment_change_request:
      type: object
      additionalProperties: false      
      description: Request of a student's enrollment / Richiesta iscrizione di una studentessa o uno studente
      properties:
        tax_code:
          type: string
          description: Tax Identification Number / Codice fiscale
          pattern: '^(?:[A-Z][AEIOU][AEIOUX]|[B-DF-HJ-NP-TV-Z]{2}[A-Z]){2}(?:[\dLMNP-V]{2}(?:A-EHLMPR-T|[DHPS][37PT][0L]|[ACELMRT][37PT][01LM]|[AC-EHLMPR-T][26NS][9V])|(?:[02468LNQSU][048LQU]|[13579MPRTV][26NS])B[26NS][9V])(?:[A-MZ][1-9MNP-V][\dLMNP-V]{2}|[A-M]0L)[A-Z]$'
          example: RSSMRA80A01F205D
          minLength: 16
          maxLength: 16
        person_id:
          type: string
          description: Unique National Identifier (ANPR ID) / Identificativo unico nazionale (ID ANPR) 
          maxLength: 9
          minLength: 9
          pattern: "^[A-Z0-9]{9}$"
          example: AB123456C
          nullable: true
        file_code:
          type: string
          description: enrollment change request code/ Codice Rettifica iscrizioni
          example: 6d183bc572f6b200015a4167
          minLength: 1
          maxLength: 64
      required:
        - tax_code
    enrollment_change_request_cancellation:
      type: object
      additionalProperties: false      
      description: Request of a student's enrollment / Richiesta iscrizione di una studentessa o uno studente
      properties:
        tax_code:
          type: string
          description: Tax Identification Number / Codice fiscale
          pattern: '^(?:[A-Z][AEIOU][AEIOUX]|[B-DF-HJ-NP-TV-Z]{2}[A-Z]){2}(?:[\dLMNP-V]{2}(?:A-EHLMPR-T|[DHPS][37PT][0L]|[ACELMRT][37PT][01LM]|[AC-EHLMPR-T][26NS][9V])|(?:[02468LNQSU][048LQU]|[13579MPRTV][26NS])B[26NS][9V])(?:[A-MZ][1-9MNP-V][\dLMNP-V]{2}|[A-M]0L)[A-Z]$'
          example: RSSMRA80A01F205D
          minLength: 16
          maxLength: 16
        person_id:
          type: string
          description: Unique National Identifier (ANPR ID) / Identificativo unico nazionale (ID ANPR) 
          maxLength: 9
          minLength: 9
          pattern: "^[A-Z0-9]{9}$"
          example: AB123456C
          nullable: true
        file_code:
          type: string
          description: enrollment change request code/ Codice Rettifica iscrizioni
          example: 6d183bc572f6b200015a4167
          minLength: 1
          maxLength: 64
      required:
        - tax_code    
        - file_code 
  requestBodies: {}
  responses: {}
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: PASETO  
servers:
  - url: 'https://localhost:8080/api'
    description: localhost
tags:
  - name: IFS04.1 - academic-enrollment-change-request
  - name: IFS04.2 - academic-enrollment-change-request-status
  - name: IFS04.3 - academic-enrollment-change-request-cancellation
  - name: IFS04.4 - enrollments-issues
  - name: health-check
  